### ISSUE TITLE
loadingMessages fails to update even after setting messageLoaded (BUG)

### ISSUE THREAD

**Issue by Minato-TW** [antoine92190/vue-advanced-chat#40] opened 2020-11-04 06:18 UTC
## Describe the bug

After switching to a new room to fetch messages, the `loadingMessages` variable fails to update resulting in infinite spinner.

## Steps to reproduce
The following snippet from my code filters messages based on the selected room and sets the `messagesLoaded` prop. 

## Expected behavior

A clear and concise description of what you expected to happen when you encounter the bug.

```
    fetchMessages: function({ room, options }) {
      this.messagesLoaded = false;
      this.messages = [];
      this.selectedRoom = room.roomId;
      this.messages = this.allMessages.filter(message => message.roomId === this.selectedRoom);
      this.messagesLoaded = true;
    }
```

## Screenshots

![c2](https://user-images.githubusercontent.com/58076350/98076243-ee2ec380-1e93-11eb-9f96-252bb928c3ae.png)

As seen in the image above, `messagesLoaded` is set to `true` but the spinner continues running. Not sure if I'm missing something obvious here.

## Device (please complete the following information)

- OS: Arch Linux 
- Browser: Firefox 81.0.2
- Package version: 0.5.1

Thank you!

**Comment by aubrydario** [comment] 2020-11-04 21:48
I can reproduce this issue. I researched a bit and think it's happening because the messages watcher doesn't get triggered and therefor `loadingMessages` doesn't get set to false.

https://github.com/antoine92190/vue-advanced-chat/blob/dc7140bea80e6da305a3f432469966a7bc2850d7/src/ChatWindow/Room.vue#L343-L371

I couldn't find a quick fix for this problem. I try again later. @antoine92190 Maybe you have an idea?

**Comment by antoine92190** [comment] 2020-11-04 22:12
`messagesLoaded ` is not used to show/hide the loading spinner, it is used to stop pagination when scrolling up.

Can you try
```
    fetchMessages: function({ room, options }) {
      this.selectedRoom = room.roomId;
      this.messages = this.allMessages.filter(message => message.roomId === this.selectedRoom);
    }
```

If not working, maybe try a workaround below

```
    fetchMessages: function({ room, options }) {
      this.selectedRoom = room.roomId;
      setTimeout(() => {
          this.messages = this.allMessages.filter(message => message.roomId === this.selectedRoom);
      }, 100)
    }
```

@aubrydario @Minato-TW In any case, could you share a full working component with dummy data so I can reproduce the issue and find a clean solution?

**Comment by antoine92190** [comment] 2020-11-04 23:42
Please also make sure you are using the latest version of the `vue-advanced-chat` package.

**Comment by Minato-TW** [comment] 2020-11-05 04:07
I still have the same issue after trying your code above. Yes, I'm using the latest version from npm. Here's a minimum reproducible component.

```javascript
<template>
  <chat-window
    :currentUserId="currentUserId"
    :rooms="rooms"
    :messages="messages"
    height="calc(100vh - 64px)"
    class="mt-16 pa-5"
    :loadingRooms="loadingRooms"
    :messagesLoaded="messagesLoaded"
    @fetchMessages="fetchMessages"
    :showNewMessagesDivider="false"
    :theme="theme"
  />
</template>
 
<script>
import ChatWindow from "vue-advanced-chat";
import "vue-advanced-chat/dist/vue-advanced-chat.css";

export default {
  components: {
    ChatWindow,
  },
  data() {
    return {
      rooms: [
        {
          roomId: "global",
          roomName: "Global Chat",
          users: [
            {
              _id: 1234,
              username: "John Doe",
              status: {
                state: "online",
                last_changed: "today, 14:30",
              },
            },
            {
              _id: 4321,
              username: "John Snow",
              status: {
                state: "online",
                last_changed: "14 July, 20:00",
              },
            },
          ],
        },
        {
          roomId: "private",
          roomName: "Private Chat",
          users: [
            {
              _id: 1234,
              username: "John Doe",
              status: {
                state: "online",
                last_changed: "today, 14:30",
              },
            },
            {
              _id: 4321,
              username: "John Snow",
              status: {
                state: "online",
                last_changed: "14 July, 20:00",
              },
            },
          ],
        },
      ],
      allMessages: [
        {
          _id: 7890,
          content: "message 1",
          roomId: "global",
          sender_id: 1234,
          username: "John Doe",
          date: "13 November",
          timestamp: "10:10",
          seen: true,
        },
        {
          _id: 3333,
          content: "message 2",
          roomId: "private",
          sender_id: 1234,
          username: "John Doe",
          date: "13 November",
          timestamp: "10:20",
          seen: true,
        },
        {
          _id: 5555,
          content: "message 2",
          roomId: "global",
          sender_id: 4321,
          username: "John Snow",
          date: "14 November",
          timestamp: "10:22",
          seen: true,
        },
      ],
      currentUserId: 1234,
      loadingRooms: false,
      messagesLoaded: true,
      messages: [],
      selectedRoom: null,
      theme: "dark",
    };
  },
  methods: {
    fetchMessages: function ({ room, options }) {
      this.selectedRoom = room.roomId;
      this.messages = this.allMessages.filter(
        (message) => message.roomId === this.selectedRoom
      );
      console.log(this.messages);
    },
  },
};
</script>
<style>
.chat-container {
  box-shadow: 0 0 4px rgb(88, 84, 84);
  border-radius: 0px !important;
}
</style>
```

As soon as I click on the private room and go back to Global, the infinite spinner starts.

Thank you.

**Comment by antoine92190** [comment] 2020-11-06 08:39
Thanks, I can reproduce the issue. I will fix this very soon

**Comment by antoine92190** [comment] 2020-11-06 09:16
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/9d0a7efb7d4e707e5a350d431825e5445e988232

**Closed by antoine92190** 2020-11-06 09:16 UTC
Labels: bug

**Comment by Minato-TW** [comment] 2020-11-06 09:35
Thanks for fixing this so quickly!

**Comment by Minato-TW** [comment] 2020-11-06 13:44
Hello,

I still seem to have the issue when one or both of the rooms have 0 messages. You can use the same code from above just with the "private" room message removed.

```javascript
      allMessages: [
        {
          _id: 7890,
          content: "message 1",
          roomId: "global",
          sender_id: 1234,
          username: "John Doe",
          date: "13 November",
          timestamp: "10:10",
          seen: true,
        },
        {
          _id: 5555,
          content: "message 2",
          roomId: "global",
          sender_id: 4321,
          username: "John Snow",
          date: "14 November",
          timestamp: "10:22",
          seen: true,
        },
      ]
```

Clicking on the private chat runs an infinite spinner instead of showing "No messages".

Thank you.

**Comment by antoine92190** [comment] 2020-11-06 14:11
This happens because you are playing with hardcoded data.
For the plugin to work properly, you need to follow loading pattern correctly, meaning that you need to update `messagesLoaded` prop every time you fetch a new room.
Hence `fetchMessages` should look like this:

```
fetchMessages: function({ room, options }) {
	this.messagesLoaded = false
	this.messages = []

        // use timeout to mimic server fetched data
	setTimeout(() => {
		this.messagesLoaded = true
	}, 0)
}
```

**Comment by Minato-TW** [comment] 2020-11-06 18:14
Thanks, that was it.

**Comment by mahdi2290** [comment] 2022-10-27 02:49
Hi, i have this code but still not working

<template>
	<vue-advanced-chat
		:current-user-id="currentUserId"
		:rooms-loaded="true"
		:rooms="JSON.stringify(rooms)"
		:messages="JSON.stringify(messages)"
		:messages-loaded="messagesLoaded"
		:room-actions="JSON.stringify(roomActions)"
		@fetch-messages="fetchMessages($event.detail[0])"
	/>
	</template>
	
	<script>
	import { register } from 'vue-advanced-chat';
	import axios from "axios";
	import loading from "@/templates/Loading.vue";
	register()
	
	export default {
		components: {
		loading,
		},
		data() {
			return {
				loading: true,
				rooms: [],
				messages: [],
				myNIK: [],
				myNIK: String(localStorage.getItem("nik")),
				roomActions: [
					{ 
						name: 'deleteRoom', 
						title: 'Hapus Pesan' 
					}
				],
				messagesLoaded: true,
				currentUserId: localStorage.getItem("nik"),
				selectedRoom: null,
				loadingRooms: false,
			}
		},
		methods: {
			init: function() {
				this.getRoom()
				this.allMessages()
			},
			getRoom: function (){
				this.myNIK = localStorage.getItem('nik');
				axios.get('chat/listing_messages/'+this.myNIK+'/').then(response => {
					var data = response.data.data
					
					const rooms = []
					for (let i = 0; i < data.length; i++) {
						rooms.push({
							roomId: data[i].to,
							roomName: data[i].name,
							avatar: 'assets/imgs/people.png',
							lastMessage: {
								_id: data[i].id,
								content: data[i].messages,
								senderId: data[i].from,
								username: data[i].name,
								timestamp: data[i].date_inserted,
								seen: true,
							},
							users: [
								{
									_id: data[i].id,
									username: data[i].name,
									avatar: 'assets/imgs/doe.png',
									status: {
										state: 'online',
										lastChanged: data[i].date_inserted,
									}
								},
							],
						})
						
					}
					this.rooms = rooms;
					this.loading = false;
				})
			},
			allMessages: function (){
				this.myNIK = localStorage.getItem('nik');
				axios.get('chat/detail_messages/'+this.myNIK+'/').then(response => {
					var data = response.data.data
					
					const messages = []
					for (let i = 0; i < data.length; i++) {
						messages.push({
							_id: data[i].id,
							roomId: data[i].to,
							content: data[i].messages,
							senderId: data[i].from,
							username: data[i].name,
							avatar: 'assets/imgs/doe.png',
							timestamp: data[i].date_inserted,
							seen: true,
						})
						
					}
	
					this.messages = messages;
				})
			},
			fetchMessages: function ({ room, options }) {
				this.selectedRoom = room.roomId;
				setTimeout(() => {
					this.messages = this.messages.filter(message => message.roomId === this.selectedRoom);
				}, 100)
				console.log(this.selectedRoom);
				console.log(this.messages);
			},
		},
		mounted() {
			this.init();
		},
	}
	</script>

i get data from Api like this:


$app->get('/detail_messages/[{nik}/]', function (Request $request, Response $response, $args) {
  try
  {
    if((isset($args['nik']))){
      $where = 'AND a.`from` = '.'"'.$args['nik'].'"';
    }else{
      $where = '';
    }

    $data = R::getAll("SELECT a.*,c.`name` AS `messages_from`, b.`name`,
                      CONCAT(b.`nik`, ' - ', b.`name`) AS `messages_to`
                      FROM `employee_notification` a
                      LEFT JOIN `employee` b ON a.`to` = b.`nik`
                      LEFT JOIN `employee` c ON a.`from` = c.`nik`
                      WHERE a.`status` != 1 ".$where." AND a.`status` IS NOT NULL
                      ORDER BY a.`date_inserted`");
    $results['data'] = $data;
    $results['message'] = 'Retrieve all Notification success';
    return $response->withStatus(200)->withHeader('Content-type', 'application/json')->withJson($results);
  }catch(Exception $e){
    $result['status'] = 4000;
    $result['message'] = $e->getMessage();
    return $response->withStatus(500)->withHeader('Content-type', 'application/json')->withJson($result);  }
});
