### ISSUE TITLE
SSR compatibility

### ISSUE THREAD

**Issue by hamimaziz** [antoine92190/vue-advanced-chat#129] opened 2021-02-11 07:55 UTC
## Describe the bug

I've implemented the chat into my vue project. The chat works correctly in the client side rendering version, but in the server side rendering version I get an error ReferenceError: HTMLDivElement is not defined.

## Additional context

Does this project support server side rendering ?
If so, how do you get it to work ?
Thank you

**Comment by antoine92190** [comment] 2021-02-11 08:24
Are you using Nuxt or any other SSR framework?

**Comment by hamimaziz** [comment] 2021-02-11 08:48
We don't use nuxt, we use @akryum/vue-cli-plugin-ssr, vue-server-renderer and expressJs

**Comment by antoine92190** [comment] 2021-02-11 08:51
Ok. I can work on SSR compatibility but could you create a minimal github repo where I can reproduce this issue?

**Comment by hamimaziz** [comment] 2021-02-14 17:32
I think we have solved this problem. One of my teammate made a plugin like this. 
```javascript
import Vue from 'vue'

async function initialized () {
    if (!process.browser) { return false }
    await import('vue-advanced-chat/dist/vue-advanced-chat.css')
    const VueChatWindow = await import('vue-advanced-chat')
    const ChatWindow = VueChatWindow.default

    // chat config plugin
    Vue.component('chat-window', ChatWindow)
}

initialized()
```
Then the chat works fine.

**Comment by antoine92190** [comment] 2021-02-14 17:43
Looks nice, but I'm not very familiar with that.
I would be happy to accept a PR if you or your teammate could add this it inside the library so everyone can benefit from it :)

**Comment by antoine92190** [comment] 2021-02-14 17:44
Or at least add this to the README so other people can have a solution to make the component work with SSR

**Comment by antoine92190** [comment] 2021-02-22 06:49
Closing this as a solution is provided

**Closed by antoine92190** 2021-02-22 06:49 UTC
Labels: bug

**Comment by pnutmath** [comment] 2021-03-01 10:16
This is not solution, it is looks like work around for SSR environment. Component is still not SSR compatible.

**Comment by wobsoriano** [comment] 2021-07-11 17:23
To actually make it work with SSR, you have to register it globally by adding it in `plugins` property and set [`mode` to `client`](https://nuxtjs.org/docs/2.x/directory-structure/plugins#object-syntax)  and also wrap the component with [client-only](https://nuxtjs.org/docs/2.x/features/nuxt-components#the-client-only-component) component from Nuxt
