### ISSUE TITLE
Slow typing speed

### ISSUE THREAD

**Issue by abbb1399** [antoine92190/vue-advanced-chat#179] opened 2021-07-06 09:40 UTC
Hi.
As messages array is bigger, as typing speed gets slower. If i have about 100~200 messages in messages prop, typing speed in text area is way too slow. How can i solve this issue?

**Comment by antoine92190** [comment] 2021-07-06 11:28
Closing this as duplicate of https://github.com/antoine92190/vue-advanced-chat/issues/153

Feel free to open a pull request to improve the performance.
Otherwise, I will try to find time to look into this.

**Closed by antoine92190** 2021-07-06 11:28 UTC
Labels: bug
