### ISSUE TITLE
 sendMessageReaction function's remove parameter get wrong value

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#66] opened 2020-12-04 09:08 UTC
`
    sendMessageReaction({roomId, messageId, reaction, remove}) {
                console.log('<sendMsgReaction>')
                console.log('roomId', roomId)
                console.log('messageId', messageId)
                console.log('reaction', reaction)
                console.log('remove', remove)
            },
`
When I remove a reaction
`
<sendMsgReaction>
roomId 5fc298782963b427d2047c03
 messageId 5fc90ff6176568191a178f62
 reaction {name: "joy"}
remove false
`
When i add a reaction(emoj)
`
<sendMsgReaction>
roomId 5fc298782963b427d2047c03
messageId 5fc90ff6176568191a178f62
 reaction {icon: "😂", name: "joy"}
 remove undefined
`
you can see, when remove emoji, the remove parameter get false, while i add an emoji, the remove is undefined.
also, when add a reaction emoji, the 
`reaction {icon: "😂", name: "joy"}
app.js:2725 remove undefined`
I means the icon parameter seems has no use, as in database side, we don't need to store it, we store like this

`
"reactions":{
 "joy":[2]
}

`
so the icon is useless.

**Comment by antoine92190** [comment] 2020-12-05 16:26
The icon param is more for information, but it does no harm to keep it.
I cannot reproduce your issue, when I remove an emoji by clicking it I get `remove: true`.
Please provide minimal component example where I can reproduce this issue.

**Comment by antoine92190** [comment] 2020-12-07 08:03
Closing until I get a reproducible example.

**Closed by antoine92190** 2020-12-07 08:03 UTC
Labels: bug
