### ISSUE TITLE
[Firebase] Heavy database usage

### ISSUE THREAD

**Issue by climentjoan** [antoine92190/vue-advanced-chat#47] opened 2020-11-17 13:01 UTC
## Describe the bug

I've implemented the chat using firebase and it is using a lot of resources with few user interaction. I've achieved the free limits in 2 hours with few users logged in.

## Steps to reproduce

Just the regular code implemented, online and typing features are disabled (I thought it was causing the problem, but it is happening even if commented)

## Expected behavior

Minimize the read and write operations.

Image https://drive.google.com/file/d/1MRXTmzdKcEssZV7fRmKyRP82LwS28up7/preview

**Comment by antoine92190** [comment] 2020-11-18 09:12
Thanks for the feedback. I will investigate.
If you have any more info don't hesitate to post it here.
You are using the demo code unchanged right?

**Comment by climentjoan** [comment] 2020-11-18 09:32
Yes, I'm using the demo code and the only things I've changed are:
- I've added auth with token on mounted().
- I've changed a bit addRoom and createRoom in order to use my own uid.
- I've disabled listenUsersOnlineStatus and listenRoomsTypingUsers lines in fetchRooms because I thought it was the problem.

If you think about how can I debug to collect more info tell me.

Thanks!

**Comment by antoine92190** [comment] 2020-11-18 18:06
You can start looking at the network tabs in chrome debug console see what's going on there.
It's probably the messages listener that causes the issue.
Anyway I will dig into it more when I get the time.

**Comment by antoine92190** [comment] 2020-11-24 07:50
I investigated with the network tabs, and nothing seems anormal.
Have you checked on your side? Do you see an unexpected number of requests in the network tabs?
Maybe I can help investigate if you give me access to your repo.

**Comment by climentjoan** [comment] 2020-11-24 09:23
Hi, I'd tried to comment some functions but I didn't detect a pattern.

With a short test, I've collected some info, 10 minutes with few interactions:
- 231 requests. 47,4 kB transferred. 162 kB resources.
- At firebase  console: 200 reads, 14 writings.

I have the .har file of the network, if you want I can send you in private.

And there is the code I'm using, it's part of an application and the only code used in the chat is:
- The component: https://github.com/climentjoan/fantasyclass/blob/master/resources/js/components/utils/Chat.vue
- The firebase config: https://github.com/climentjoan/fantasyclass/blob/master/resources/js/components/utils/firestore/index.js

Thanks!

**Comment by saumyasinghal747** [comment] 2020-11-25 20:25
> I investigated with the network tabs, and nothing seems anormal.
> Have you checked on your side? Do you see an unexpected number of requests in the network tabs?
> Maybe I can help investigate if you give me access to your repo.

I also noticed this, my firebase quota is already 3% full from firestore writes - I only sent 3 messages to one user.

**Comment by antoine92190** [comment] 2020-11-26 09:15
@climentjoan I see that your code makes twice more request than my original demo code when sending a message.
I will dig into it more this week end, but there is something that can be improved with your code.

**Comment by antoine92190** [comment] 2020-11-26 09:15
@saumyasinghal747 Are you using the original demo code ?

**Comment by antoine92190** [comment] 2020-11-27 16:54
I think the culprit is `typingMessage` method. It fires at every keystroke when writing a message.
To keep this feature and avoid unecessary firestore writes, you could change your method to:
```
typingMessage({ message, roomId }) {
	// Add this line
	if (message.length > 1) return;

	const dbAction = message
		? firebase.firestore.FieldValue.arrayUnion(this.currentUserId)
		: firebase.firestore.FieldValue.arrayRemove(this.currentUserId)
	roomsRef.doc(roomId).update({
		typingUsers: dbAction
	})
},
```

**Comment by antoine92190** [comment] 2020-11-27 17:08
Please check that and let me you if it solves your issue: https://github.com/antoine92190/vue-advanced-chat/commit/7c6ca161568522348cf8695231c202e357ced7f5

**Comment by climentjoan** [comment] 2020-11-28 08:52
Thanks @antoine92190!

I've been testing the changes but I'm noticing a lot of readings just opening the chat.

- Load the page, 4 chatrooms:
   - Readings: 68
   - Writings:  2
Isn't the readings too high for just 4 chatrooms?

Then, I enter a chatroom, and type a message:
   - Readings: 79
   - Writings: 5

Then I left the chat opened for 10 minutes without interaction:
   - Readings: 97
   - Writings: 5

**Comment by antoine92190** [comment] 2020-11-28 09:42
During this test, have you opened only one chat or several (on other devices or tabs)?

**Comment by climentjoan** [comment] 2020-11-28 10:52
Just one tab

**Comment by antoine92190** [comment] 2020-11-29 09:43
How did you get those numbers? I'm trying to check Cloud Firestore usage, but the write & reads don't update in realtime so it's difficult to have accurate results.

The first loading is higher, because when loading the page, all chatroom and last messages are loaded, then the room on top of the list automatically opens and loads the last 20 messages. But 68 is indeed a bit too high.

**Comment by antoine92190** [comment] 2020-11-29 10:27
Using https://console.cloud.google.com/firestore/usage with my demo code I get:

Load page:
- Reads: 59
- Writes: 1

Send a message:
- Reads: 63 (+4)
- Writes: 4 (+3)

Send another message:
- Reads: 67 (+4)
- Writes: 7 (+3)

After 20 minutes of inactivity
- Reads: 67 (+0)
- Writes: 7 (+0)

**Comment by climentjoan** [comment] 2020-11-29 13:30
I wait 5-10 minutes to read the changes.

New test (4 chats, the first one with 3 messages):

First load:
- 50 Reads
- 2 writes

Change Room
- 65 Reads (+15) 
- 3 writes (+1)

Send a message:
- 75 Reads (+10)
- 6 writes (+3)

Wait 30 minutes:
- 82 Reads (+7)
- 6 Writes (+0)

The network console shows this:
https://drive.google.com/file/d/1V1fKmGw-38i5mSjuGxgORRlEmYNWcaFc/view?usp=sharing

All are requests like:
https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2Ftest%2Fdatabases%2F(default)&gsessionid=xxx&VER=8&RID=rpc&SID=xxx=0&AID=347&TYPE=xmlhttp&zx=xxx&t=1

It seems it is not so high now. With this records per user I think it could be manageable, but I don't understand the first 50 reads, only 4 chatrooms with 3 messages in the first one (the one is loaded at refresh), or the 10 reads in sending a message.

**Comment by antoine92190** [comment] 2020-11-29 16:37
I tracked each method that reads the DB and I got:
- Fetch Rooms: +4 => 4 rooms in total
- Fetch Room Users: +9 => each room has 2 or 3 users
- Fetch Last Room Message: +4 => 1 for each room
- Listen Last Room Message: +4 => 1 for each room
- Listen Rooms Typing Users: +4 => 1 for each room
- Fetch Room Messages: +6 => 4 messages, then 2 more for checking pagination
- Listen Room Messages: +6 => same as the one above

The total is 37.
- "Fetch Last Room Message" and "Listen Last Room Message" can probably be merged to have 4 calls instead of 8
- "Fetch Room Messages" and "Listen Room Messages" can also be merged to have 6 calls instead of 12

So total would be 27.
I'm still investigating, will write down results here.

**Comment by antoine92190** [comment] 2020-11-29 16:40
Also, I see in your repo that `sendMessage` method has:
- `const room = await query.get()` => it's not used so you can remove it
-  `let users = await roomsRef.doc("" + roomId)` => can also be removed as you already have the users in the `sendMessage` params.
Doing this will remove 3 reads when sending  a message

**Comment by antoine92190** [comment] 2020-11-29 16:48
Also this commit should reduce db usage: https://github.com/antoine92190/vue-advanced-chat/commit/b5fc5eb276ba12e034d520778caa622831ca8968

**Comment by antoine92190** [comment] 2020-11-29 17:02
I also found this interesting post: https://stackoverflow.com/a/56434555
Meaning that during your tests you should not keep your Firestore console open

**Comment by antoine92190** [comment] 2020-11-29 18:17
> Fetch Last Room Message and Listen Last Room Message can probably be merged to have 4 calls instead of 8

Fixed: https://github.com/antoine92190/vue-advanced-chat/commit/849785ad1c94effad0e9f483bb0bd36a8e2f321f

**Comment by antoine92190** [comment] 2020-11-29 22:12
> Fetch Room Users can be optimized to avoid fetching current user and duplicated users

Fixed: https://github.com/antoine92190/vue-advanced-chat/commit/37ff443a63544e9823c3e5d52437cd8d72f1d6a8

**Comment by antoine92190** [comment] 2020-11-29 22:46
After those optimizations, total of writes went from 37 to 28.

This biggest one remains though:
> Fetch Room Messages and Listen Room Messages can also be merged to have 6 calls instead of 12
If you have 50 messages in a room, then there will be 50*2 = 100 writes.
I will fix that but it will take more time as it's difficult change.

**Comment by climentjoan** [comment] 2020-11-30 09:26
Thanks @antoine92190 ! Great work! I'll try your fixes.

Also, to avoid unnecessary reads, could be interesting to not load the last room by default, as we don't know if the user wants to load it.

**Comment by antoine92190** [comment] 2020-11-30 18:36
> Also, to avoid unnecessary reads, could be interesting to not load the last room by default, as we don't know if the user wants to load it.

I think this is the expected behaviour, but I can add a prop to disable that behaviour.

**Comment by climentjoan** [comment] 2020-11-30 19:33
I've checked both WhatsApp and Telegram webchats, and they are not showing any chats until you select a chatroom.

Having a prop is a good choice BTW.

Thanks! Your project is awesome.

**Comment by antoine92190** [comment] 2020-11-30 20:06
`loadFirstRoom ` prop added in https://github.com/antoine92190/vue-advanced-chat/commit/83466c015b45cb65ebceae5ee396a72af933f343

**Comment by climentjoan** [comment] 2020-12-01 08:18
Great! :D I'm unable to update via npm, could be because the version is still 0.5.5?

**Comment by antoine92190** [comment] 2020-12-01 08:27
I just updated to 0.5.6

**Comment by antoine92190** [comment] 2021-02-13 14:42
I am closing this as most issues have been tackled.
> Fetch Room Messages and Listen Room Messages can also be merged to have 6 calls instead of 12
This is causing UI/UX issues so I will keep the current logic for now

**Closed by antoine92190** 2021-02-13 14:42 UTC
Labels: bug
