### ISSUE TITLE
[Improvement] Add typescript types declaration (index.d.ts)

### ISSUE THREAD

**Issue by LouisMazel** [antoine92190/vue-advanced-chat#77] opened 2020-12-11 09:10 UTC
## Is your feature request related to a problem? Please describe

When we use your library with Vue/Nuxt application with Typescript, we have an error message something like that: `Type declaration is missing`

## Describe the solution you'd like

The minimal solution is to add `index.d.ts` of the root lib folder, like this:

```js
// index.d.ts
declare module 'vue-advanced-chat'
```

**Comment by antoine92190** [comment] 2020-12-11 11:49
Sounds good, don't hesitate to make a pull request if you want this to be fixed asap

**Comment by antoine92190** [comment] 2020-12-12 11:26
I created a Nuxt project with Typescript, but I couldn't see any `Type declaration is missing` error.
It seems to work fine on my side without `index.d.ts` file. Could you let me know how I can reproduce?
Any help to improve Nuxt & Typescript compatibility is much appreciated :)

**Comment by LouisMazel** [comment] 2020-12-13 14:40
Have you set the strict mode of Typescript ?

**Comment by antoine92190** [comment] 2020-12-14 07:52
Yes, I have `"strict": true` in my `tsconfig.json`

**Comment by LouisMazel** [comment] 2020-12-17 13:41
Resolved in # 91 and pending deployment to npm

**Comment by antoine92190** [comment] 2020-12-18 18:26
Released in v.0.5.7

**Comment by antoine92190** [comment] 2020-12-19 11:49
@LouisMazel The travis build is failing since the implementation of typescript:
https://travis-ci.com/github/antoine92190/vue-advanced-chat/builds/209822282

```
> vue-advanced-chat@0.5.8 gen:types /home/travis/build/antoine92190/vue-advanced-chat
> tsc --declaration
dist/vue-advanced-chat.js:1:10 - error TS9005: Declaration emit for this file requires using private name '(Anonymous function)'. An explicit type annotation may unblock declaration emit.
```

I update typescript version without success. Do you have any clue?

**Comment by antoine92190** [comment] 2020-12-19 16:30
Actually, the build fails because of this specific line:
https://github.com/antoine92190/vue-advanced-chat/blob/master/src/ChatWindow/RoomsList.vue#L108

No idea why, for some reason travis don't like `format-links` syntax. Will investigate.

**Comment by antoine92190** [comment] 2020-12-19 16:46
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/24982cc4265428e1af641ae5b0ceb89ad51c8d76

**Closed by antoine92190** 2020-12-19 16:46 UTC
Labels: enhancement
