### ISSUE TITLE
in Safari 13.1.1 mojave, the reaction emoji popup cannot show up

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#69] opened 2020-12-04 18:17 UTC
In chrome and firefox, reaction emoji click will popup a list of emoji icons (such as smile, joy etc.), but in safari, the emoji click wont open up the window to select an emoji. Please fix it. thanks.

**Comment by antoine92190** [comment] 2020-12-05 15:48
I cannot reproduce this issue. Do you see any error in the console?

**Comment by tingan** [comment] 2020-12-05 16:28
<img width="671" alt="Screenshot 2020-12-05 at 6 27 35 PM" src="https://user-images.githubusercontent.com/356031/101255119-9bad2500-3727-11eb-8190-546271f42f51.png">
no error, the emoji-picker element is there, just css problem.

**Comment by antoine92190** [comment] 2020-12-05 16:36
Can you try and play around with css in safari debug console? Maybe change something like:
```
.emoji-picker {
  z-index: 9999;
  ...
}
```

**Comment by antoine92190** [comment] 2020-12-05 16:42
Unfortunately, I cannot debug this issue as I am on macOS Big Sur using Safari 14.0.1
You can probably fork the repo and play around with css file in https://github.com/antoine92190/vue-advanced-chat/blob/master/src/ChatWindow/EmojiPicker.vue

**Comment by antoine92190** [comment] 2020-12-05 16:44
Once your forked the repo, maybe try this: https://stackoverflow.com/a/40896165
```
.emoji-picker {
  -webkit-transform:translate3d(0,0,0);
  ...
}
```

**Comment by antoine92190** [comment] 2020-12-05 16:47
Another thing you can try is to remove `overflow: hidden;` from `.col-messages`:
https://github.com/antoine92190/vue-advanced-chat/blob/f5fe787a6c340cb6727b1e0faf1e76ac546ee7a7/src/ChatWindow/Room.vue#L782-L789

**Comment by tingan** [comment] 2020-12-05 17:01
ok, tried -webkit-transform:translate3d(0,0,0); and have played with css console, no luck yet.

**Comment by tingan** [comment] 2020-12-12 12:34
![Uploading Screenshot 2020-12-12 at 2.34.31 PM.png…]()

**Comment by antoine92190** [comment] 2020-12-12 12:42
The issue above is not related to this topic. Please open a new issue.

**Comment by antoine92190** [comment] 2020-12-12 12:46
Is it related to the issue that the emoji popup cannot show up?
If you have cloned the repo, can you try to replace https://github.com/antoine92190/vue-advanced-chat/blob/2c84243ae005d7df9d9a96b432a1feb9b497e2da/src/ChatWindow/EmojiPicker.vue#L86-L93 by:
```
openEmoji(ev) {
  this.$emit('openEmoji', true)
  this.setEmojiPickerPosition(
    ev.clientY,
    ev.view.innerWidth,
    ev.view.innerHeight
  )
},
```

**Comment by tingan** [comment] 2020-12-12 12:55
ok, it's related, as the error only show in safari.

**Comment by antoine92190** [comment] 2021-01-10 22:47
Can you reproduce this issue with the demo website?
https://antoine92190.github.io/vue-advanced-chat/

**Comment by antoine92190** [comment] 2021-01-15 20:59
I'm closing the issue as I cannot reproduce. If you are still facing the issue please comment here.

**Closed by antoine92190** 2021-01-15 20:59 UTC
Labels: bug
