### ISSUE TITLE
Sending messages and entering rooms gets very slow if you have a room with a lot of messages

### ISSUE THREAD

**Issue by Hugo01** [antoine92190/vue-advanced-chat#383] opened 2022-10-27 13:55 UTC
## Describe the bug
Hello, first of all, thank you for all the amazing work you did on this library, truly fantastic.
So, this is what happens, everything seems to work fairly well when you have around 100-200 messages loaded
after that you start to feel that sending a message becomes slower after each message, ultil it gets to a point where it takes 7-10 seconds for the message to appear on screen
I have a hunch that this could be the v-for on "room-message" inside the Room.vue component that is probably taking to long to render all these messages

**This problem seems much worst when you're on a mobile device**

## Steps to reproduce

I've created a repo that simulates the problem
https://gitlab.com/hugo6467/vue-advanced-chat-demo
You only need to run:

- **yarn install**
- **yarn dev --host (important to use the --host flag to expose the local ip address to your network)**
- **grab a phone**
- **enter your local ip address on the phone browser, for instance:  "http://192.168.25.81:3000/"**
- **Click on the "Lots of Messages ROOM"**
- **Send a message**

**Comment by antoine92190** [comment] 2022-10-27 15:01
Closing this as it’s a duplicate of https://github.com/antoine92190/vue-advanced-chat/issues/342

**Closed by antoine92190** 2022-10-27 15:01 UTC
Labels: bug
