### ISSUE TITLE
slot attributes are deprecated | Vue 2.6+

### ISSUE THREAD

**Issue by palmtown** [antoine92190/vue-advanced-chat#444] opened 2023-04-03 01:39 UTC
## Describe the bug

The slot attribute has been depreciated as shown at https://github.com/vuejs/rfcs/blob/master/active-rfcs/0001-new-slot-syntax.md and https://github.com/vuejs/rfcs/blob/master/active-rfcs/0002-slot-syntax-shorthand.md.  When provided by this component, the code will fail to compile.

## Steps to reproduce

Use the below example as shown at https://github.com/antoine92190/vue-advanced-chat using Vue.js 2.6 or greater.

`div v-for="message in messages" :slot="'message-avatar_' + message._id">
    New Avatar
  </div>`

## Expected behavior

Avatar shown next to message

## Device (please complete the following information)

- OS: Windows 10
- Browser: Chrome  Version 111.0.5563.147 (Official Build) (64-bit)
- Package version: 2.0.6

## Additional context

This issue is related to https://github.com/antoine92190/vue-advanced-chat/issues/412 that was closed, however, the proposed solution did not fix the issue.

**Comment by antoine92190** [comment] 2023-04-03 07:03
I don't have the issue on my side. Can your reproduce on this minimal example? https://github.com/antoine92190/vue-advanced-chat-sandbox

**Comment by antoine92190** [comment] 2023-04-12 07:12
Actually I'm not using vue slots, but native web slots: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots
So I guess it's an misinterpretation of the eslint-plugin-vue.
What error are you getting when running `npm install` on the sandbox?

**Comment by antoine92190** [comment] 2023-04-16 17:43
Closing this as it seems to be an issue with `eslint-plugin-vue`. Please reopen otherwise

**Closed by antoine92190** 2023-04-16 17:43 UTC
Labels: bug
