### ISSUE TITLE
The automatic scrolling button does not hide when it reaches the end.

### ISSUE THREAD

**Issue by AlandEr2612** [antoine92190/vue-advanced-chat#92] opened 2020-12-16 20:14 UTC
## Describe the bug

The automatic scrolling button does not hide when it reaches the end, this means that the complete content of the messages is not read.

## Screenshots

![image](https://user-images.githubusercontent.com/9408682/102401471-5ef7ee00-3fb1-11eb-8ded-ea56fcc956de.png)

**Comment by antoine92190** [comment] 2020-12-17 08:52
I cannot reproduce. Can you share your component code snippet, even with fake data as long as I can reproduce

**Comment by AlandEr2612** [comment] 2020-12-17 23:24
Component
```
<b-container class="geh-container py-3" fluid v-if="isLoggedIn">
    <b-row class="h-100">
        
        <b-col class="h-100" md="4" xs="12">
            <vue-advanced-chat class="h-100" :currentUserId="user.GUID" :loadingRooms="true"
                :menuActions="menuActions" :messageActions="messageActions" :messages="messages"
                :messagesLoaded="messagesLoaded" :rooms="rooms" :singleRoom="true" @fetchMessages="fetchMessages"
                @menuActionHandler="menuActionHandler" @openFile="openFile" @sendMessage="sendMessage" />
        </b-col>
    </b-row>
</b-container>
```
Data Room

```
[
   {
      "roomId":"13c6c988_e596_4550_ae86_6ae6a41b4a5a",
      "roomName":"TEST",
      "avatar":"https://localhost:44396/wap/geh/telemedicina/img/logo_global.png",
      "unreadCount":0,
      "lastMessage":{
         
      },
      "users":[
         {
            "_id":"BOOT",
            "username":"BOOT",
            "avatar":"https://localhost:44396/wap/geh/telemedicina/img/default-profile-icon.png",
            "status":{
               "state":"online",
               "last_changed":"2020-12-17 06:18"
            }
         },
         {
            "_id":"f0d6071a_20a2_48a1_ab66_bbd8abb1bb6b",
            "username":"TEST_1",
            "avatar":"https://localhost:44396/wap/geh/marketplace/files/person/2adba87f_6d4f_4986_a2bf_4b83670d8d27/photo/Diseño Borrador (1) (1).png",
            "status":{
               "state":"online",
               "last_changed":"2020-12-17 06:18"
            }
         },
         {
            "_id":"269b87c4_6960_41fc_9cf7_c3faf614c317",
            "username":"TEST_2",
            "avatar":"",
            "status":{
               "state":"online",
               "last_changed":"2020-12-17 18:18"
            }
         }
      ],
      "typingUsers":[
         
      ]
   }
]
```

Data Messages
```
[
   {
      "_id":"d800f0c5-c077-4c78-a042-abf849cde6f8",
      "content":"Hola...",
      "sender_id":"269b87c4_6960_41fc_9cf7_c3faf614c317",
      "username":"TEST_2",
      "date":"17 diciembre",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"ee5e46c0-aa2a-4bcb-9bb2-5360dfc8dd3b",
      "content":"Hola...",
      "sender_id":"f0d6071a_20a2_48a1_ab66_bbd8abb1bb6b",
      "username":"TEST_1",
      "date":"17 December",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"6201a7d4-39b7-43cb-a543-0b3e6bc68499",
      "content":"Hola...",
      "sender_id":"f0d6071a_20a2_48a1_ab66_bbd8abb1bb6b",
      "username":"TEST_1",
      "date":"17 December",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"ae08a435-9f2e-466b-8e6f-5f20a40b2675",
      "content":"Hola...",
      "sender_id":"269b87c4_6960_41fc_9cf7_c3faf614c317",
      "username":"TEST_2",
      "date":"17 diciembre",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"65c4ad9d-675b-4336-b5ed-8c2b262b5512",
      "content":"Hola...",
      "sender_id":"269b87c4_6960_41fc_9cf7_c3faf614c317",
      "username":"TEST_2",
      "date":"17 diciembre",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"85ac210c-82a2-44be-b45d-ca211b01b090",
      "content":"Hola...",
      "sender_id":"f0d6071a_20a2_48a1_ab66_bbd8abb1bb6b",
      "username":"TEST_1",
      "date":"17 December",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"74cf1702-da52-4c65-86de-d39e6067786a",
      "content":"Hola...",
      "sender_id":"f0d6071a_20a2_48a1_ab66_bbd8abb1bb6b",
      "username":"TEST_1",
      "date":"17 December",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"7f5aeb61-671f-4fe2-944c-de724f1da76f",
      "content":"Hola...",
      "sender_id":"269b87c4_6960_41fc_9cf7_c3faf614c317",
      "username":"TEST_2",
      "date":"17 diciembre",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"fde45a30-c563-473c-9012-dc1e6ffabb7c",
      "content":"Hola...",
      "sender_id":"269b87c4_6960_41fc_9cf7_c3faf614c317",
      "username":"TEST_2",
      "date":"17 diciembre",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"dea4f33f-947a-41c1-b625-3168e8705900",
      "content":"Hola...",
      "sender_id":"f0d6071a_20a2_48a1_ab66_bbd8abb1bb6b",
      "username":"TEST_1",
      "date":"17 December",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"a9305c24-dfb5-4602-b047-d4e84ddde84b",
      "content":"Hola...",
      "sender_id":"f0d6071a_20a2_48a1_ab66_bbd8abb1bb6b",
      "username":"TEST_1",
      "date":"17 December",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"af148407-0c17-46eb-b1e3-9fb5a425d7e8",
      "content":"Hola...",
      "sender_id":"269b87c4_6960_41fc_9cf7_c3faf614c317",
      "username":"TEST_2",
      "date":"17 diciembre",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"a9868125-aca6-4a80-b2a6-f11cdcf0f35d",
      "content":"Hola...",
      "sender_id":"269b87c4_6960_41fc_9cf7_c3faf614c317",
      "username":"TEST_2",
      "date":"17 diciembre",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"b70451e3-8c80-42f1-be09-a8dd7b27800d",
      "content":"Hola...",
      "sender_id":"f0d6071a_20a2_48a1_ab66_bbd8abb1bb6b",
      "username":"TEST_1",
      "date":"17 December",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"4da22221-f269-482e-809b-7e824c054df7",
      "content":"Hola...",
      "sender_id":"f0d6071a_20a2_48a1_ab66_bbd8abb1bb6b",
      "username":"TEST_1",
      "date":"17 December",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"b1c2e691-f540-4e45-ab31-0f50d4013c62",
      "content":"Hola...",
      "sender_id":"269b87c4_6960_41fc_9cf7_c3faf614c317",
      "username":"TEST_2",
      "date":"17 diciembre",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"1a9678a2-f607-4130-ac87-309fe4df666a",
      "content":"Hola...",
      "sender_id":"269b87c4_6960_41fc_9cf7_c3faf614c317",
      "username":"TEST_2",
      "date":"17 diciembre",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"c623ff9f-89c5-4768-8a62-d0f20c58b75e",
      "content":"Hola...",
      "sender_id":"f0d6071a_20a2_48a1_ab66_bbd8abb1bb6b",
      "username":"TEST_1",
      "date":"17 December",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"b15bbc07-ab4d-44bb-8b3b-5bfa20e79ae0",
      "content":"Hola...",
      "sender_id":"f0d6071a_20a2_48a1_ab66_bbd8abb1bb6b",
      "username":"TEST_1",
      "date":"17 December",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":null,
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"f8984914-5143-4d7c-bdae-af9108662acb",
      "content":"",
      "sender_id":"f0d6071a_20a2_48a1_ab66_bbd8abb1bb6b",
      "username":"TEST_1",
      "date":"17 December",
      "timestamp":"18:18",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":{
         "blob":"[object Blob]",
         "name":"rx_torax",
         "size":100776,
         "type":"jpg",
         "localUrl":"blob:https://localhost:44396/3c3da3bb-19c3-4a45-9cb0-89be3d1b5252",
         "url":"https://localhost:44396/wap/geh/telemedicina/files/13c6c988_e596_4550_ae86_6ae6a41b4a5a/rx_torax.jpg"
      },
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   },
   {
      "_id":"aee6d7f5-ef51-48a6-be8b-7e0a16927ab5",
      "content":"WhatsApp Video 2020-11-07 at 12.27.52.mp4",
      "sender_id":"269b87c4_6960_41fc_9cf7_c3faf614c317",
      "username":"TEST_2",
      "date":"17 diciembre",
      "timestamp":"18:19",
      "system":false,
      "saved":true,
      "distributed":true,
      "seen":true,
      "disable_actions":false,
      "disable_reactions":false,
      "file":{
         "blob":{
            
         },
         "name":"WhatsApp Video 2020-11-07 at 12",
         "size":1371248,
         "type":"27",
         "localUrl":"blob:https://localhost:44396/6bd620a3-0bd6-42f2-bf2b-21f77961a785",
         "url":"https://localhost:44396/wap/geh/telemedicina/files/13c6c988_e596_4550_ae86_6ae6a41b4a5a/WhatsApp Video 2020-11-07 at 12.27"
      },
      "reactions":{
         "wink":[
            
         ],
         "laughing":[
            
         ]
      }
   }
]
```

**Comment by AlandEr2612** [comment] 2020-12-17 23:31
![ChatBugScroll](https://user-images.githubusercontent.com/9408682/102556055-00f10680-4096-11eb-9e85-ab7a816cc33b.gif)

**Comment by AlandEr2612** [comment] 2020-12-18 14:43
It's weird, it seems like it is a problem with the screen resolution, usually my screen resolution is in 4k, but I just reduced it to Full HD and the button hides properly.

**Comment by antoine92190** [comment] 2020-12-18 18:26
Could you check if the issue is solved in v.0.5.7?

**Comment by AlandEr2612** [comment] 2020-12-18 19:41
At first I thought there were more bugs, but I think it was the cache, so far everything in order.

**Comment by antoine92190** [comment] 2020-12-18 19:44
Ok I'm closing this issue then. Let me know if you see any bugs related to this in the thread.

**Closed by antoine92190** 2020-12-18 19:44 UTC
Labels: bug
