### ISSUE TITLE
How can i adjust the room list width, on wide screen device ?

### ISSUE THREAD

**Issue by boypanjaitan16** [antoine92190/vue-advanced-chat#32] opened 2020-10-06 05:15 UTC
Can you help about adjusting the width of room list panel please ?

**Comment by antoine92190** [comment] 2020-10-06 08:27
You can play around with the `rooms-container` CSS class to adjust the room list width.
Default values are:
```
flex: 0 0 25%;
min-width: 260px;
max-width: 500px;
```
So if you override those, you can probably achieve what you want without breaking the design.

**Comment by boypanjaitan16** [comment] 2020-10-06 08:51
one more thing, how to reduce the search box width, so the add button can appear perfectly
![image](https://user-images.githubusercontent.com/46698152/95180116-bd536400-07eb-11eb-8ce4-421b5f669156.png)

**Comment by antoine92190** [comment] 2020-10-06 10:10
Which browser are you using? And which operating system?

**Comment by boypanjaitan16** [comment] 2020-10-06 10:13
I'm using firefox on centOS

**Comment by antoine92190** [comment] 2020-10-06 10:18
Ok, I can reproduce this issue. I will fix it.

However, I see there are 2 magnifying glasses icons in the search bar. Have you done anything to get that?

I also see that emojis are not shown correctly. I cannot reproduce on macOS, so if you could figure out why this issue appears I would be grateful! Please see https://github.com/antoine92190/vue-advanced-chat/issues/24

**Comment by boypanjaitan16** [comment] 2020-10-06 10:21
About that duplicated magnifying glasses icons maybe it's caused by my another css, but it's okay for now. But thank you for your quick response

**Comment by antoine92190** [comment] 2020-10-06 10:53
Add button display fixed in https://github.com/antoine92190/vue-advanced-chat/commit/00f62dda13f2c897c69294932c6a6675e81da020

**Closed by antoine92190** 2020-10-06 10:53 UTC
