### ISSUE TITLE
An icon/image to identify multi communication channels

### ISSUE THREAD

**Issue by ycarooliveira** [antoine92190/vue-advanced-chat#201] opened 2021-08-31 13:06 UTC
## Is your feature request related to a problem? Please describe

Isn't related to any problem

## Describe the solution you'd like

I have my own service that handles the _chat backend_ and I thought what if I want to have more channels to chat with? Like Telegram, WhatsApp and Messenger? And would be a _Room_ prop like the avatar

## Describe alternatives you've considered

Something like this,
![Captura de Tela 2021-08-31 às 10 02 52](https://user-images.githubusercontent.com/71798108/131507304-ca44eec2-665d-4eb0-ac15-56ea1c6ac398.png)
(image shameless copied from Chatwoot)

## Additional context

I already did this feature on my own, I'm just opening this _Issue_ to know if @antoine92190 thinks would be fine to do a PR.

**Comment by ferretwithaberet** [comment] 2021-09-02 19:10
In my opinion, it would be better to make the whole avatar a scoped slot, this way you get more control over the functionality of the avatar.

**Comment by antoine92190** [comment] 2021-09-07 05:37
I agree with avatar slot. Duplicate of https://github.com/antoine92190/vue-advanced-chat/issues/194

**Closed by antoine92190** 2021-09-07 05:37 UTC
Labels: enhancement
