### ISSUE TITLE
When scroll icon displayed, adding new message doesn't scroll screen to the bottom.

### ISSUE THREAD

**Issue by martynishin** [antoine92190/vue-advanced-chat#139] opened 2021-02-26 17:37 UTC
## Describe the bug

When I have a lot of messages and scroll up, the scroll icon is appear. After that I add new message and send. In this moment my screen doesn't scroll to the bottom, it stay in the same place. On the other hand, if I scroll down till the scroll icon disappear, and add new message after that, than screen automatically scroll to the bottom (expected behaviour).

## Steps to reproduce

1. Load a lot of messages.
2. Scroll up untill scroll icon is appear.
3. Add new message and send.
4. If the scroll icon not shown, all works fine.

## Expected behavior

After adding a new message screen scroll down to this message automatically.

## Device (please complete the following information)

MacBook Pro 15"

**Comment by antoine92190** [comment] 2021-02-26 17:46
I cannot reproduce. Which version of the chat are you using?
Can you send a GIF of the issue so I can try to reproduce?

**Comment by martynishin** [comment] 2021-02-26 17:54
> I cannot reproduce. Which version of the chat are you using?
> Can you send a GIF of the issue so I can try to reproduce?

**Comment by martynishin** [comment] 2021-02-26 17:55
Version 0.7.8

**Comment by martynishin** [comment] 2021-02-26 18:06
> I cannot reproduce. Which version of the chat are you using?
> Can you send a GIF of the issue so I can try to reproduce?


![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/20871977/109337798-0cb73100-786e-11eb-9e87-69f472deb6da.gif)

**Comment by antoine92190** [comment] 2021-02-27 09:14
Have you change the height of the textarea? Maybe it's breaking the scrolling behaviour.
If you did, could you revert it to default and see if it fixes the issue?

**Comment by martynishin** [comment] 2021-02-27 18:17
No, I haven't change the height of the textarea and didn't use :height prop.
But if I try to use this prop and pass any value, scrolling behaviour still incorrect.

Below you can see an example of my Chat component:
<template>
    <div>
        <chat-window
            :current-user-id="currentUserId"
            :rooms="rooms"
            :messages="messages"
            :show-audio="false"
            :show-files="true"
            :show-emojis="false"
            :show-reaction-emojis="false"
            :show-add-room="false"
            :messages-loaded="messagesLoaded"
            :loading-rooms="false"
            :rooms-loaded="true"
            @send-message="sendMessage"
            @fetch-messages="fetchMessages"
        />
    </div>
</template>

**Comment by antoine92190** [comment] 2021-02-28 06:56
I still cannot reproduce. The textarea doesn't have the same height as on the demo, maybe you are overriding it in your css.
If not, could you please share your project or a minimal reproducible example so I can debug it?

**Comment by martynishin** [comment] 2021-02-28 15:18
Try to do it on the clear project. Just follow the next steps:
1. Use code snippet below.
2. yarn add vue-advanced-chat
3. yarn run watch

```
<template>
    <div>
        <chat-window
            :current-user-id="currentUserId"
            :rooms="rooms"
            :messages="messages"
            @send-message="sendMessage"
            @fetch-messages="fetchMessages"
        />
    </div>
</template>

<script>
import ChatWindow from 'vue-advanced-chat'
import 'vue-advanced-chat/dist/vue-advanced-chat.css'

export default {
    name: 'Chat',

    components: {
        ChatWindow
    },
    
    data() {
        return {
            messages: [],
            rooms: [
                {
                    roomId: 1,
                    roomName: 'Room 1',
                    avatar: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/NafSadh_Profile.jpg/768px-NafSadh_Profile.jpg',
                    index: 3,
                    users: [
                        {
                            _id: 1234,
                            username: 'John Doe',
                            avatar: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/NafSadh_Profile.jpg/768px-NafSadh_Profile.jpg',
                            status: {
                                state: 'online',
                                lastChanged: 'today, 14:30'
                            }
                        },
                        {
                            _id: 4321,
                            username: 'John Snow',
                            avatar: 'https://lh3.googleusercontent.com/-G1d4-a7d_TY/AAAAAAAAAAI/AAAAAAAAAAA/AAKWJJPez_wX5UCJztzEUeCxOd7HBK7-jA.CMID/s83-c/photo.jpg',
                            status: {
                                state: 'offline',
                                lastChanged: '14 July, 20:00'
                            }
                        }
                    ],
                    typingUsers: [ 4321 ]
                }
            ],
            currentUserId: 1234,
        }
    },
    
    methods: {
        fetchMessages() {
            setTimeout(() => {
                let messages = [];

                for (let i=0; i<30; i++) {
                    messages.push({
                        _id: i,
                        content: 'message 1',
                        senderId: 1234,
                        username: 'John Doe',
                        date: '13 November',
                        timestamp: '10:20',
                        system: false,
                        saved: false,
                        distributed: false,
                        seen: false,
                        disableActions: true,
                        disableReactions: true,
                    })
                }

                this.messages = messages;
            }, 2000);
        },
        sendMessage(message) {
            const m = {
                _id: this.messages.length,
                content: message.content,
                senderId: this.currentUserId,
                timestamp: new Date()
            }

            this.$set(this.messages, this.messages.length, m)
        },
    },
}
</script>
```

**Comment by antoine92190** [comment] 2021-02-28 18:06
I can reproduce thanks. Will try to fix this ASAP

**Comment by antoine92190** [comment] 2021-02-28 18:48
In the meantime, you can do:
```
this.messages = [...this.messages, m]
```
Instead of:
```
 this.$set(this.messages, this.messages.length, m)
```

**Comment by antoine92190** [comment] 2021-02-28 18:55
Also, I'm curious about the height of your textarea.
When you get the time, could you send me a screenshot using this repo: https://github.com/antoine92190/vue-advanced-chat-sandbox

**Comment by martynishin** [comment] 2021-02-28 20:04
<img width="1125" alt="Снимок экрана 2021-02-28 в 22 03 39" src="https://user-images.githubusercontent.com/20871977/109431773-dbc33180-7a10-11eb-8f27-21dc983016a0.png">

hope this help

**Comment by antoine92190** [comment] 2021-02-28 20:26
Thanks. Which browser are you using?

**Comment by martynishin** [comment] 2021-02-28 20:39
Google Chrome
Version 88.0.4324.192 (Official Build) (x86_64)

**Comment by antoine92190** [comment] 2021-03-02 08:34
Scroll behaviour is fixed in https://github.com/antoine92190/vue-advanced-chat/commit/70cfa0026744829865b7ab6cb65db8be7b47e45f

**Closed by antoine92190** 2021-03-02 08:34 UTC
Labels: bug

**Comment by martynishin** [comment] 2021-03-03 12:06
I've found the new issue. With the same code for fetch messages on the first page load, if the last message belongs to the current user, then already is fine. If the last message belongs to another user, then scroll works incorrectly. See screenshots below.
<img width="1059" alt="Снимок экрана 2021-03-03 в 14 01 49" src="https://user-images.githubusercontent.com/20871977/109803342-9af23500-7c29-11eb-81e6-abb024bc7662.png">
<img width="1059" alt="Снимок экрана 2021-03-03 в 14 02 14" src="https://user-images.githubusercontent.com/20871977/109803345-9c236200-7c29-11eb-8b86-bd3ea752f111.png">
