### ISSUE TITLE
The selected shown room and the selected room in rooms list is different if you open a room programmatically

### ISSUE THREAD

**Issue by duhoang00** [antoine92190/vue-advanced-chat#366] opened 2022-09-27 15:07 UTC
## Describe the bug
The shown room and the selected room in rooms list is different if you open a room by changing the prop `room-id`

## Steps to reproduce
1. Open a room by clicking on it in rooms list
2. Change the prop `room-id` to open a room (by a custom element)
3. It shows correct room
4. But the rooms list still showing the old selected room

## Expected behavior
The opened room is the same with selected room in the rooms list

## Device

- OS: Ubuntu 20.04.4 LTS
- Browser: Brave 1.43.93
- Package version: 2.0.3

**Comment by NINI1988** [comment] 2022-10-05 23:50
For me it works with v2.0.3 and firefox under windows 11.

Maybe you change the room list and changing the roomId at the same time?
Then add a timeout to set the roomId:
```js
setTimeout(()` => {
  // This timeout is required so that the chat component has updated its room list
  this.roomId = 1398
}, 0)
```

Or could you post a running example?

**Comment by antoine92190** [comment] 2022-10-30 15:15
I cannot reproduce either. Closing this until we can a reproducible example

**Closed by antoine92190** 2022-10-30 15:15 UTC
Labels: bug
