### ISSUE TITLE
Handle the send message event on Enter key press

### ISSUE THREAD

**Issue by shahil16** [antoine92190/vue-advanced-chat#278] opened 2022-01-27 15:55 UTC
When we use to type the message using Japanese text then we get the suggestion dropdown. If we select the option from the dropdown by pressing the enter key then the "send-message" events get triggered. We need some functionality to handle this scenario.

**Comment by antoine92190** [comment] 2022-01-30 09:57
I cannot reproduce. Which chat version are you using? Which browser? Can you share a video?

**Comment by antoine92190** [comment] 2022-02-08 08:06
Closing this until I get more information

**Comment by thu-san** [comment] 2022-04-29 06:05
I have forked shift+enter to send message and using this for now.
@antoine92190 Could you please check if it's fit for merge.
https://github.com/antoine92190/vue-advanced-chat/pull/304

**Comment by natsumework** [comment] 2022-04-29 19:14
Same issue.

This problem only occurs on my mac, it works fine on my windows and android.

**Comment by itTkm** [comment] 2022-05-01 13:44
I have faced same problem.
Then I have tried #304, it was work fine for me.

**Comment by natsumework** [comment] 2022-05-01 14:52
I thing we can use [KeyboardEvent.isComposing](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing) property or [compositionstart/compositionend](https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event) event to determine whether the user is selecting word from a list.

```
this.getTextareaRef().addEventListener('keyup', e => {
    if (e.key === 'Enter' && !e.isComposing && !e.shiftKey && !this.fileDialog) {
        ...
```

**Comment by itTkm** [comment] 2022-06-03 08:40
Hello @antoine92190,
I investigated the [error that occurred in CI](https://github.com/antoine92190/vue-advanced-chat/runs/6721353539?check_suite_focus=true#step:4:267).
This error only occurs if the typescript version is 4.7, so we can use v4.6.x as a workaround.

I have created new PR for this workaround: #315 
Could you please confirm this changes?

**Closed** 2022-06-03 10:39 UTC
Labels: enhancement, in progress
