### ISSUE TITLE
__webpack_modules__[moduleId] is not a function

### ISSUE THREAD

**Issue by setterlee** [antoine92190/vue-advanced-chat#340] opened 2022-08-17 13:39 UTC
## Describe the bug

The component is failing on mouting with a webpack module error

`Uncaught (in promise) TypeError: __webpack_modules__[moduleId] is not a function
    at __webpack_require__ (vue-advanced-chat.common.js?91b2:30462:1)
    at eval (vue-advanced-chat.common.js?91b2:30559:1)
    at eval (vue-advanced-chat.common.js?91b2:42585:1)
    at Object.eval (vue-advanced-chat.common.js?91b2:42588:1)
    at eval (vue-advanced-chat.common.js:42591:30)
    at ./node_modules/vue-advanced-chat/dist/vue-advanced-chat.common.js (12.js:80:1)
    at __webpack_require__ (app.js:854:30)
    at fn (app.js:151:20)
    at eval (ChatContainer.vue?2b8c:34:1)
    at ./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/@vue/cli-service/node_modules/vue-loader-v16/dist/index.js?!./src/components/chat/ChatContainer.vue?vue&type=script&lang=js (12.js:35:1)`

## Steps to reproduce

Im using the talbar/next version for vue3 and this error appear at mounting point. 

## Expected behavior

See the chat component 

## Device 

- OS: Windows 11 (npm running under WSL: Ubuntu)
- Browser:  Chrome 104.0.5112.81
- Package version: https://github.com/antoine92190/vue-advanced-chat/tarball/next

**Comment by antoine92190** [comment] 2022-08-20 08:32
Difficult to know what's happening.
Would you mind sharing your repo, or a minimal reproducible example?

**Comment by setterlee** [comment] 2022-08-20 12:09
> Difficult to know what's happening. Would you mind sharing your repo, or a minimal reproducible example?

Sure, here a repo to reproduce [demo-vue3-chat](https://github.com/setterlee/demo-vue3-chat)

I tested with node 14.17.0, 16.17 and finally with 18.7.0 and same results...

**Comment by cainiao1231** [comment] 2022-08-23 08:11
I seem to have the same problem, I opened a project from a few months ago and it worked fine at first, but when I tried to delete node_module and then npm install.I got a similar error, and my project page was blank , I want to know what to do.

**Comment by antoine92190** [comment] 2022-08-23 17:49
I’ll have a look ASAP

**Comment by devilbits** [comment] 2022-08-24 10:12
Having the same issue

**Comment by antoine92190** [comment] 2022-08-24 21:23
I can reproduce the issue with the repo you sent, however I cannot reproduce when testing with a new empty vue 3 project.
It looks like you need to upgrade the vue CLI to version 5. 
Everything works fine when I replace your devDependencies with:

```
  "devDependencies": {
    "@vicons/carbon": "^0.12.0",
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-eslint": "~5.0.0",
    "@vue/cli-plugin-router": "~5.0.0",
    "@vue/cli-plugin-vuex": "~5.0.0",
    "@vue/cli-service": "~5.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.32.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.0.0",
    "naive-ui": "^2.32.1",
    "prettier": "^2.2.1",
    "sass": "^1.45.1",
    "sass-loader": "^10.2.0",
    "vfonts": "^0.1.0",
    "vue-loader-v16": "^16.0.0-beta.5.4"
  }
```

**Comment by antoine92190** [comment] 2022-08-25 21:31
By the way, I strongly recommend that you use the new web component version of this library instead of the vue 3 branch, as this will soon replace the current library.
You can use the library with vue 3 using this dependency `"vue-advanced-chat": "https://github.com/antoine92190/vue-advanced-chat/tarball/vite"`
You can check the installation steps in the READM file of the `vite` branch, and the migration guide here: https://github.com/antoine92190/vue-advanced-chat/pull/332

**Comment by antoine92190** [comment] 2022-08-26 21:16
I just released the 2.0.0 version which should solve your issue. Can someone try it out and let me know if it works?

**Comment by antoine92190** [comment] 2022-08-28 06:57
Closing this as it should be resolved. Please reopen otherwise.

**Closed by antoine92190** 2022-08-28 06:57 UTC
Labels: bug

**Comment by cainiao1231** [comment] 2022-08-28 12:37
The new version works great, thank you very much for your selfless open source dedication. I'm just a rookie, your project really helped me a lot, I look forward to it getting better and better and allowing more people to use your project. Peace and love！

**Comment by setterlee** [comment] 2022-08-28 14:52
I have no chance to test it right now but thanks to @cainiao1231 to verify the fix.. Thanks a lot @antoine92190
