### ISSUE TITLE
Message is undefined, message input either

### ISSUE THREAD

**Issue by Langriklol** [antoine92190/vue-advanced-chat#289] opened 2022-02-26 11:54 UTC
## Describe the bug

After finding out how I should pass rooms and messages I found an issue while writing a new message. After I click into the message input, value of input changes to undefined and throw 2 errors in console as shown on figure 1.

## Steps to reproduce

1. Use CDN variant
2. Wrap it into custom component
3. Get it look like shown on figure 2
4. Try to type into message input

## Expected behavior

Allows me to write and send message I type.

## Screenshots

Figure 1:
![image](https://user-images.githubusercontent.com/20239181/155842069-33ca5356-3150-411b-8d4e-d6027b8bc737.png)

Figure 2:
![image](https://user-images.githubusercontent.com/20239181/155842120-44db573e-caf7-47fb-8d41-ea9c3113519d.png)

## Device (please complete the following information)

- OS: Windows 10
- Browser: Firefox 95
- Package version: latest for Vue2 (26. 2. 2022)

**Comment by Langriklol** [comment] 2022-03-04 08:57
@antoine92190 any suggestions/fixes already available? :)

**Comment by antoine92190** [comment] 2022-03-04 10:11
I will check this week-end and keep in touch

**Comment by antoine92190** [comment] 2022-03-06 09:59
I cannot reproduce when installing the component with:
```
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-advanced-chat@1.5.3/dist/vue-advanced-chat.min.js"></script>
```

**Comment by antoine92190** [comment] 2022-03-11 17:36
Did you try the imports I sent above?

**Comment by antoine92190** [comment] 2022-03-24 21:02
Closing this as the fix above should fix your issue. Please reopen otherwise.

**Closed** 2022-03-24 21:02 UTC
Labels: bug
