### ISSUE TITLE
Firestore sync error

### ISSUE THREAD

**Issue by hassantahir448studio** [antoine92190/vue-advanced-chat#208] opened 2021-09-10 11:14 UTC
##BUG

While we're using the public 1 to many chat where multiple people are using the chat to communicate, there is a moment where 
for some users, the chat stop syncing. The user is unable to send or receive new messages. The user has to refresh the page to be able to sync to the chat again. This often happens where there are multiple people are using the public chat. And the occurrence of this issue is not timely and rather randomly. 

In our Network section of the browser developer console, we found out that at some instance, one or more GET calls are failing randomly, thus returning an error code of 400 saying "**Your client has issued a malformed or illegal request. Unknown SID"**

Screenshots of the issue are attached below.

## Steps to reproduce

To reproduce the error you can initiate the group conversation, while keeping your network tab open to see the GET and POST calls. After some time you'll observe some calls which failed due to the error stated above. This issue persists not only in our custom project but in the Demo Chat App provided by you. 

## Screenshots

![image](https://user-images.githubusercontent.com/88437396/132845135-48638883-69f0-4863-b80e-e92059269ec1.png)
![unknownSSID](https://user-images.githubusercontent.com/88437396/132845160-7725028f-fbc0-45d5-9b09-ad4a010009da.PNG)

## Device 

The issue has been observed in Chrome, Edge, Firefox, Opera in mobile as well as desktop.

**Comment by antoine92190** [comment] 2021-09-11 06:25
I'm having a hard time to reproduce.
I'm in a chat room with two users, sent 100+ messages and didn't see the error.
Do you see any error in your debug console?

**Comment by hassantahir448studio** [comment] 2021-09-13 04:34
> I'm having a hard time to reproduce.
> I'm in a chat room with two users, sent 100+ messages and didn't see the error.
> Do you see any error in your debug console?


After initiating conversation, I waited between 3- 7 minutes and started observing error in the Network Console. However, debug console showed no error. It is just one of the GET call kept failing.

**Comment by hassantahir448studio** [comment] 2021-09-13 07:47
Like here, I started the conversation at 12:15 by sending a message, and kept my Network Console opened. After 20 minutes, the error appeared randomly. And it isn't necessary that it should appear after 20 minutes. Sometimes it takes 5 - 10 minutes and sometimes it takes more than 10 minutes for the error to appear. Which is why the appearance of the error is not consistent rather unexpected1
![Uploading tempsnip.png…]()

**Comment by jonmalave** [comment] 2021-11-10 16:48
@hassantahir448studio are you still experiencing this problem? I'm curious as I was interested in purchasing the premium version, but i'm not so sure at the moment if this remains an unresolved issue.

**Comment by hassantahir448studio** [comment] 2021-11-11 04:40
@jonmalave  Well, I haven't used it that much after that. Although I applied a fix at firestore but I am not sure whether it is working or not.

**Comment by antoine92190** [comment] 2021-11-11 09:36
@hassantahir448studio Which fix did you apply?

**Comment by hassantahir448studio** [comment] 2021-11-11 09:41
@antoine92190   I added db.settings({ experimentalForceLongPolling: true }) in my firebase.js file. This enabled the long polling. I haven't received any complain after implementing this fix.

**Comment by antoine92190** [comment] 2021-11-14 17:09
@hassantahir448studio Thanks, will check that.
I just update the demo to Firebase 9, maybe the issue was fixed with this migration.
Could you check if the issue is fixed? Otherwise I will implement your fix

**Comment by hassantahir448studio** [comment] 2021-11-15 04:45
> @hassantahir448studio Thanks, will check that. I just update the demo to Firebase 9, maybe the issue was fixed with this migration. Could you check if the issue is fixed? Otherwise I will implement your fix

Sure i will update you if the error still exists

**Comment by antoine92190** [comment] 2021-11-23 07:19
I’m closing this as it may be fixed with Firestore 9. Please reopen otherwise.

**Closed by antoine92190** 2021-11-23 07:19 UTC
Labels: bug
