### ISSUE TITLE
[Vue warn]: <transition-group> children must be keyed: <div>

### ISSUE THREAD

**Issue by an-liu1** [antoine92190/vue-advanced-chat#1] opened 2020-02-12 21:58 UTC
[Vue warn]: <transition-group> children must be keyed: <div>  
The project can not run because of the <transition-group>

**Comment by antoine92190** [comment] 2020-02-12 22:21
Hi,

All your messages must have the `_id` property. This property is used as the key for transition-group:

```
messages="[
  {
    content: 'message 1',
    sender_id: 1234,
    username: 'John Doe',
    date: '13 November',
    timestamp: '10:20',
  }
]"
```
It was indeed missing in the documentation. I just added it :) Thanks!

**Comment by antoine92190** [comment] 2020-03-05 08:22
@an-liu1 I'm closing this issue. If you still have difficulties to make this work please let me know

**Closed by antoine92190** 2020-03-05 08:22 UTC

**Comment by Steuls** [comment] 2020-03-09 13:18
@antoine92190  I am also getting this issue but I have included _id in all my messages. Please see the screenshots attached. I get this error with another one but the data for the message seems to be find.
![vuechat1](https://user-images.githubusercontent.com/45470638/76216388-6e6b2f00-6208-11ea-9e48-c69a71ee1309.PNG)
![vuechat2](https://user-images.githubusercontent.com/45470638/76216395-7034f280-6208-11ea-9e9b-20f04cab0348.PNG)

**Comment by antoine92190** [comment] 2020-03-09 20:04
@Steuls Maybe you forgot to set `messagesLoaded` to `true` after all your messages have been loaded. See docs: https://github.com/antoine92190/vue-advanced-chat#props-api
Can you check this?

Else could you share the code you implemented?

**Comment by Steuls** [comment] 2020-03-10 08:44
@antoine92190 I am setting messagesLoaded to true. I am using the vuex store a lot for data transfer but here is the component: 
`<template>
  <chat-window
    :rooms="rooms"
    :messages="messages"
    :messagesLoaded="messagesLoaded"
    :currentUserId="currentUserId.toString()"
    :menuActions="menuActions"
    height="800px"
    @fetchMessages="fetchMessages"
    @menuActionHandler="menuActionHandler"
  />
</template>

<script>
  import ChatWindow from 'vue-advanced-chat';
  import 'vue-advanced-chat/dist/vue-advanced-chat.css';

  export default {
    name: 'ChatPage',
    components: {
      ChatWindow
    },
    data() {
      return {
        pagination: 0,
        menuActions: [
          {
            name: 'changeName',
            title: 'Change Room Name'
          },
          {
            name: 'leaveGroup',
            title: 'Leave Group'
          },
          {
            name: 'inviteGroup',
            title: 'Invite to Group'
          }
        ]
      };
    },
    computed: {
      currentUserId() {
        return this.$store.state.user.id;
      },
      messages() {
        return this.$store.state.messages ? this.$store.state.messages.all : [];
      },
      rooms() {
        return this.$store.state.messages
          ? this.$store.state.messages.latest
          : [];
      },
      messagesLoaded: {
        set(newVal) {
          this.$store.commit('setMessagesLoaded', newVal);
        },
        get() {
          return this.$store.state.messagesLoaded;
        }
      }
    },
    methods: {
      fetchMessages({ room, options }) {
        if (options && options.reset) {
          this.pagination = 0;
          this.$store.commit('resetMessages');
        }
        this.$store.dispatch('loadMessages', {
          loaded: this.pagination,
          roomId: room.roomId
        });
        this.pagination += 100;
      },
      // eslint-disable-next-line no-unused-vars
      menuActionHandler({ room, action }) {
        switch (action) {
          case 'changeName':
            break;
          case 'leaveGroup':
            break;
          case 'inviteGroup':
            break;
        }
      }
    },
    beforeCreate() {
      this.$store.dispatch('loadChats');
      this.$socket.emit('login', {
        token: this.$store.state.jwtToken.accessToken,
        name: this.$store.state.user.username
      });
    }
  };
</script>
` 
The relevant bit of the store is just a http request:
`loadMessages(context, payload) {
      http
        .get('/chatApi/room', {
          params: {
            numberLoaded: payload.loaded,
            roomId: payload.roomId
          },
          headers: {
            Authorization: `Bearer ${context.state.jwtToken.accessToken}`
          }
        })
        .then(response => {
          context.commit('setAllMessages', response.data);
        })
        .catch(e => console.log(e.response));`
the commit is:
`setAllMessages(state, payload) {
      state.messages.all = payload;
      state.messagesLoaded = true;
    }`

**Comment by antoine92190** [comment] 2020-03-10 12:46
@Steuls I tried to reproduce the issue using your code, but without success.
Can you try to make the chat work with hardcoded messages data?
So we can identify if the issue comes from your backend or the vuex store implementation.
Another way I can help would be to give me access to your repo.

**Comment by Steuls** [comment] 2020-03-10 13:59
It was a problem with my data coming in, I was using a spread operator incorrectly to join messages to the array. Sorry for the issue.
