### ISSUE TITLE
Question about fetch-messages event

### ISSUE THREAD

**Issue by wzl778633** [antoine92190/vue-advanced-chat#313] opened 2022-05-26 11:00 UTC
Firstly, really nice work for chat plugins, a big appreciate for this project.
But I’m a little bit lost with the documentation. Right now I want to figure out the core event fetch-messages, here is my code for the callback function: 
```
getThisRoomMessage({room, options} = data){
      //this is the var for messages-loaded prop
      this.message_fullyLoad_flag = false;
      this.rightNowRoomId = room.roomId;
    
      setTimeout(() => {
        let tmp = [ {
          _id: Math.random()*1000,
          indexId: Math.random()*1000,
          content: '<usertag>1234</usertag> test test test test test test ',
          senderId: 4321,
          username: 'qwe',
         ........
          usersTag:[
            {
              _id: 1234,
              username: 'John Doe',
              avatar: 'assets/imgs/doe.png',
              status: {
                state: 'online',
                lastChanged: 'today, 14:30'
              }
            },
          ]
        },
        ..... * 10 random messages,];
        tmp = tmp.concat(this.messages);
        this.messages = tmp;
        this.message_fullyLoad_flag = false;
      },3000)
    },
```
What I want to do is to make an infinite message loading loop to imitate loading with backend data. Each time I scroll up will load 10 more random messages. But right now it will only load once (when the room is opened) and then it will show the loading icon forever and never trigger this event again no matter how I scroll up, did I missing something? I cannot find some useful information about this part So I want to know why and how to solve this.
Also, the user tag that I set (format I showed above) for random messages will always shows “@unknown” in the chat room. I didn’t find any documentation about user tags logic. Could you explain more about how this part works?
I will really appreciate your help!

**Comment by antoine92190** [comment] 2022-06-03 06:47
- You need to have enough messages when the room is opened so the infinite loader is not visible (hidden by the scroll). You can try to load 20 or 30 messages initially and it may fix your issue.
- For the usertag to work you need to set the content message as you did: `content: '<usertag>1234</usertag> test test test test test test'`, but you also need to have the matching user in the `rooms.users` prop: https://github.com/antoine92190/vue-advanced-chat#rooms-prop

**Comment by oxavibes** [comment] 2022-06-09 06:10
@antoine92190 

> * You need to have enough messages when the room is opened so the infinite loader is not visible (hidden by the scroll). You can try to load 20 or 30 messages initially and it may fix your issue.
> * For the usertag to work you need to set the content message as you did: `content: '<usertag>1234</usertag> test test test test test test'`, but you also need to have the matching user in the `rooms.users` prop: https://github.com/antoine92190/vue-advanced-chat#rooms-prop

Hi @antoine92190 , the thing is we need to stop the loader after messages has been loaded to hide the loader but if we set messagesLoaded to true the scroll will not work right? What are we missing?

**Comment by antoine92190** [comment] 2022-06-09 06:59
The loader should automatically disappear as soon as at least one message is added. You don't need to do anything to manage the central loader.
`messagesLoaded` should be used when there is no more messages to load, or if there are 0 messages to load initially.

**Comment by oxavibes** [comment] 2022-06-09 16:31
> The loader should automatically disappear as soon as at least one message is added. You don't need to do anything to manage the central loader. `messagesLoaded` should be used when there is no more messages to load, or if there are 0 messages to load initially.

Understood, i'll check my logic then. Thank you for you quick response!

**Comment by antoine92190** [comment] 2022-06-10 07:08
Please let me know if you solved it so we can close this issue.

**Comment by wzl778633** [comment] 2022-06-10 07:52
@antoine92190 Thanks for your help! But I cannot solve problem 1 with your solution. I already load 30+ messages initially, But the infinite message loading loop still not working: in my scenario, when my site route to the chatroom page, the chat page will automatically scorll up a little bit. When I scroll to the top of this room, it will show the loading icon but never load new messages again. It will only load once (when I first open this room). I never set `messagesLoaded` to `true` but seems the `fetch-messages (getThisRoomMessage)` never get called again.
![image](https://user-images.githubusercontent.com/55415793/173017312-8602f821-535a-4513-b6ea-84ff309e2139.png)
![image](https://user-images.githubusercontent.com/55415793/173018001-c711f14f-e03b-4831-b25b-dcf46b15bb4c.png)

**Comment by antoine92190** [comment] 2022-06-10 07:56
Strange, would it be possible to have access to your project so I can reproduce and fix the issue?

**Comment by wzl778633** [comment] 2022-06-10 08:00
> Strange, would it be possible to have access to your project so I can reproduce and fix the issue?

I will try to make a demo to see if I can let you access it! Thanks!

**Comment by wzl778633** [comment] 2022-06-10 08:46
@antoine92190 After I tired, is hard to make a demo for my scenario isolated with my project. :( But I can share my screen or something like that to let you remotely control or testing (via zoom or something like that), is that ok for you?

**Comment by oxavibes** [comment] 2022-06-10 15:06
@antoine92190 Fetch messages is called twice when i click on a chatroom is that a normal behaviour?

**Comment by antoine92190** [comment] 2022-06-10 15:43
@wzl778633 Can you first send me a video from the moment you load the app until the bug appears?

**Comment by wzl778633** [comment] 2022-06-11 05:06
@antoine92190 https://youtu.be/rCwExOOO7xE Here is the video for the bugs description :)

**Comment by Morrowi** [comment] 2022-09-20 11:41
Hello! Thanks for your work. This is a super project!
I have a problem, the event is not called when scrolling messages up, there are no additional @fetch-messages calls, so I can’t load more messages, maybe I’m doing something wrong ?
I use the link where you can see the code I attach https://github.com/Morrowi/kabinet_kdm/blob/2a6bc559967c184f7b128a2ca9d908d7b0854797/src/components/BoardUser.vue#L558

I use socket to receive already formatted messages from the server and add them to the :messages="messages" property.

**Comment by antoine92190** [comment] 2022-09-21 06:40
Please use version 2.0.3, previous versions are not supported anymore.
This issue is probably fixed by https://github.com/antoine92190/vue-advanced-chat/issues/354

**Comment by Morrowi** [comment] 2022-09-21 11:05
Спасибо за ответ. Но у меня возникла новая проблема, при регистрации компонента в браузере (в консоле) вылетает ошибка на register(); https://github.com/Morrowi/kabinet_kdm/blob/dev/src/components/BoardUser.vue#L280 
во  vue.config.js зарегистрировал
module.exports = {
    chainWebpack: config => {
        config.module
            .rule('vue')
            .use('vue-loader')
            .tap(options => ({
                ...options,
                compilerOptions: {
                    // treat any tag that starts with ion- as custom elements
                    isCustomElement: tagName => tagName === 'vue-advanced-chat'
                }
            }))
    },
    outputDir:'home/public/',
    configureWebpack: {
        devServer: {
            headers: { "Access-Control-Allow-Origin": "*" },
            watchOptions: {
                ignored: [/public/],
            }
        }
    },

}

<img width="1668" alt="image" src="https://user-images.githubusercontent.com/14123077/191488590-b36ceedd-1cb5-4c24-8a89-a4d9b326980c.png">

**Comment by antoine92190** [comment] 2022-09-21 11:56
@Morrowi Please read the README file, you are not using the component correctly: https://github.com/antoine92190/vue-advanced-chat#usage

**Comment by Morrowi** [comment] 2022-09-21 14:16
> @MorrowiПожалуйста, прочтите файл README, который содержит стандартный компонент: [https://github.com/antoine92190/vue-advanced-chat#usage.](https://github.com/antoine92190/vue-advanced-chat#usage)

Thank you for your time.
I also tried calling the component as described in the README, I'm attaching the link.
But I have the same error, it swears at register(); Object(...) is not a function.
Please tell me what can I do wrong

https://github.com/Morrowi/kabinet_kdm/blob/dev/src/components/BoardUser.vue#L240

**Comment by antoine92190** [comment] 2022-09-22 06:43
The `next` branch is not maintained anymore. Please install the version from npm: `npm install vue-advanced-chat`

**Comment by antoine92190** [comment] 2022-09-22 06:56
Actually, I see you updated the version in the dev branch. I made it work on you branch, you need to:
- Change the dependency to `"vue-advanced-chat": "2.0.3",`
- Remove the below code from your codebase, and update the old chat implementation in your `Chat.vue` file:
```
//import ChatWindow from 'vue-advanced-chat'
// import 'vue-advanced-chat/dist/vue-advanced-chat.css'
```

**Comment by Morrowi** [comment] 2022-09-22 08:16
@antoine92190 Thanks for helping me. I did everything as you wrote, but the result is the same.
he swears at register(); https://github.com/Morrowi/kabinet_kdm/blob/dev/src/components/BoardUser.vue#L278

I'm already starting to go crazy
Perhaps I'm registering the component incorrectly? Although I do as described in the documentation https://vuejs.org/guide/extras/web-components.html#using-custom-elements-in-vue

**Comment by Morrowi** [comment] 2022-09-22 09:43
@antoine92190 Yes, I did it all. But the error is still the same

**Comment by antoine92190** [comment] 2022-09-22 10:24
Strange, I cloned your project and it works on my side. Which browser are you using? And which node version?

**Comment by antoine92190** [comment] 2022-09-22 11:24
You forgot to stringify some props. Please double check your code.

<img width="1236" alt="Screenshot 2022-09-22 at 13 22 20" src="https://user-images.githubusercontent.com/16256207/191734320-4dca1bae-5189-47a8-ab3f-f5ee225f6ff9.png">

**Comment by Morrowi** [comment] 2022-09-22 11:31
I specified the details, but the problem remained. All changes to git

**Comment by antoine92190** [comment] 2022-09-22 11:43
Try to delete the whole project locally, and clone it again. If it works on my side it should work on your side.
If it doesn't work, please open a new discussion, as it is not related to the original issue.

**Comment by Morrowi** [comment] 2022-09-22 14:37
Thank you! For a long time! That helped!

**Comment by antoine92190** [comment] 2022-09-25 18:11
@crystal96 @wzl778633 @oxavibes Can any of you reproduce the issue with latest chat version `2.0.3`?

**Comment by antoine92190** [comment] 2022-09-30 13:42
Closing this due to inactivity. Please reopen if the issue still exists.

**Closed by antoine92190** 2022-09-30 13:42 UTC

**Comment by MaxZhurin** [comment] 2023-08-21 13:16
Good afternoon
 I can not understand. @fetch-messages="fetchMessages($event.detail[0])" is only called once when the chat is opened. when I scroll to the top nothing happens and @fetch-messages is not called a second time.
 
chat single room and messages a lot
 
 what could it be?
 
 windows 11, last chrome
 
  "vue-advanced-chat": "^2.0.7",
