### ISSUE TITLE
'fetch-more-rooms' not fired if rooms list shows scroll

### ISSUE THREAD

**Issue by PhantomYdn** [antoine92190/vue-advanced-chat#165] opened 2021-04-28 03:52 UTC
## Describe the bug

We have a huge list of rooms to be displayed. So we expected to use mentioned pagination for rooms loading if use scrolls down. But we have found out nesty bug: if an initially loaded list is shorter vertically (so no scroll appeared for rooms list) - everything is fine and 'fetch-more-rooms' fired, but once we have list longer vertically and scroll appeared - no more 'fetch-more-rooms' happens.

Just compare the following 2 screens of vue events:
First one: initially loaded list is longer than vertical side:

![image](https://user-images.githubusercontent.com/1199285/116343911-3ae7bd00-a79a-11eb-88e4-35771094a412.png)

Second one: initially loaded list is short - than incrementally it was growing to required height - and after reaching big enough (but not all required rooms) size - it stopped loading.

![image](https://user-images.githubusercontent.com/1199285/116343715-d7f62600-a799-11eb-8bfb-8ab917f6f7b3.png)

## Expected behavior

Even if there is a scroll: component should try to load more till `rooms-loaded=true`

## Device (please complete the following information)

- OS: Win10
- Browser: Chrome
- Package version: 0.8.4

**Comment by PhantomYdn** [comment] 2021-04-28 04:02
One more thing to consider: list of rooms might be dynamic. So if right now rooms are fully loaded: later rooms list can grow and loading will be needed. I see per code, that there is some "points of no return" - when rooms considered to be loaded - and that's it: no further attempts to allow inifine loading.

**Comment by PhantomYdn** [comment] 2021-04-28 04:28
I just made it working back by the following changes in CSS:

![image](https://user-images.githubusercontent.com/1199285/116346542-599c8280-a79f-11eb-972b-53b5c2614610.png)

For my needs - it's OK, but probably by doing that mobile support becomes broken.

**Comment by ycarooliveira** [comment] 2021-04-30 23:08
The problem is with _force-use-infinite-wrapper_ in RoomList.vue [here](https://github.com/antoine92190/vue-advanced-chat/commit/9feea5591528922a4d379030b68658f1f0af3afc#diff-3506adde10750d9e7ffeca1922e8df5e87ad5ddf08adc831bbc33ff9709e1fc1)

there is two ways to solve this, remove the props _force-use-infinite-wrapper_ or change the value  to _.vac-room-list_

**Comment by ycarooliveira** [comment] 2021-04-30 23:22
The problem is with _force-use-infinite-wrapper_ in RoomList.vue [here](https://github.com/antoine92190/vue-advanced-chat/commit/9feea5591528922a4d379030b68658f1f0af3afc#diff-30860b5091c054a938c4e9f49b26011ea637f22b370a83b918c5d5efee2413ff)

there is two ways to solve this, remove the props _force-use-infinite-wrapper_ or change the value  to _.vac-room-list_

**Comment by antoine92190** [comment] 2021-04-30 23:25
@ycarooliveira Thanks for the help! I'll check in the coming days

**Comment by antoine92190** [comment] 2021-05-01 09:15
> One more thing to consider: list of rooms might be dynamic. So if right now rooms are fully loaded: later rooms list can grow and loading will be needed. I see per code, that there is some "points of no return" - when rooms considered to be loaded - and that's it: no further attempts to allow inifine loading.

@PhantomYdn Could you open a new issue for that?

**Comment by antoine92190** [comment] 2021-05-01 09:16
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/3c0b67ae5de5c368711acaeff9f5ef7f03535d6c

**Comment by PhantomYdn** [comment] 2021-05-03 20:39
Just btw... 0.8.5 made things even worse: no it's loading infinitely even if you didn't scroll down. Fixing that by switching back to 0.8.4 for now.

**Comment by ycarooliveira** [comment] 2021-05-05 19:38
Sorry, it worked for me, I can't reproduce this error on 0.8.5

**Comment by PhantomYdn** [comment] 2021-05-08 15:26
@ycarooliveira , how many loads needed in your case to load all rooms? Probably, they just quickly passed through. In our case, it's around 15k, so it's being invoked, invoked and invoked even if user is not scrolling down... Will try to check what can be done on 0.8.5. to eliminate such behavior.

**Comment by antoine92190** [comment] 2021-05-30 07:21
@PhantomYdn Did you find a solution for this? I couldn't reproduce.
Can you try to reproduce using https://github.com/antoine92190/vue-advanced-chat-sandbox?

**Comment by PhantomYdn** [comment] 2021-05-30 14:27
@antoine92190  - will try to reproduce. Potentially it's some mess with our custom css styles. Thanks for the great library!

**Comment by antoine92190** [comment] 2021-06-05 07:51
Ok will close that for now. Please reopen if you have more info

**Closed by antoine92190** 2021-06-05 07:51 UTC
Labels: bug
