### ISSUE TITLE
Spinner errors

### ISSUE THREAD

**Issue by temirlankasen** [antoine92190/vue-advanced-chat#35] opened 2020-10-25 18:30 UTC
Hey. I wanted to try using your chat. Installed through npm. I added the necessary parameters, but when sending a message, I get an error from the spinner. What could be wrong?
Even when I just try to run your code and another question.

```
<template>
  <chat-window
    :currentUserId="1234"
    :rooms="rooms"
    :loadingRooms="loadingRooms"
    :messages="messages"
    :messagesLoaded="messagesLoaded"
  >
  </chat-window>
</template>

<script>
import ChatWindow from 'vue-advanced-chat'
import 'vue-advanced-chat/dist/vue-advanced-chat.css'

export default {
  components: {
    ChatWindow
  },

  data() {
    return {
      rooms: [],
      loadingRooms: true,
      messages: [],
      messagesLoaded: false
    }
  },

  mounted() {
    this.rooms = [
      {
        roomId: 1,
        roomName: 'Room 1',
        unreadCount: 4,
        lastMessage: {
          content: 'Last message received',
          sender_id: 1234,
          username: 'John Doe',
          timestamp: '10:20',
          date: 123242424,
          seen: false,
          new: true
        },
        users: [
          {
            _id: 1234,
            username: 'John Doe',
            status: {
              state: 'online',
              last_changed: 'today, 14:30'
            }
          },
          {
            _id: 4321,
            username: 'John Snow',
            status: {
              state: 'offline',
              last_changed: '14 July, 20:00'
            }
          }
        ],
        typingUsers: [4321]
      }
    ]

    this.messages = [
      {
        _id: 12345,
        roomId: 1,
        content: 'Heeeey',
        sender_id: 4321,
        username: 'Tu',
        date: '13 November',
        timestamp: '10:20',
        seen: true,
        disable_actions: false,
        disable_reactions: true
      }
    ]

    this.loadingRooms = false
    this.messagesLoaded = true
  }
}
</script>
```

![Fe6mcasMJ3A](https://user-images.githubusercontent.com/48218803/97115714-5e19ad00-1722-11eb-9178-ee61eff3949e.jpg)

**Comment by antoine92190** [comment] 2020-10-26 11:46
I cannot reproduce this error.
Could you give me access to your repo so I can have a look? Or a minimal example that I can run to reproduce the error.

**Comment by temirlankasen** [comment] 2020-10-26 18:33
https://github.com/temirlankasen/naimi_admin_chat

I take data from api. data format from the documentation in the repository

**Comment by antoine92190** [comment] 2020-10-26 18:53
I cannot run the project, there is an error.
I cloned the project, ran `yarn install` then `npm run dev` and get:

```
Error: EROFS: read-only file system, mkdir '/static'
```

Please let me know how I can run the project without any error.

**Comment by antoine92190** [comment] 2020-10-29 14:08
I'm closing this issue until I can reproduce the error.

**Closed by antoine92190** 2020-10-29 14:08 UTC
