### ISSUE TITLE
2.0.0 bugs

### ISSUE THREAD

**Issue by 1259549061** [antoine92190/vue-advanced-chat#348] opened 2022-09-02 07:19 UTC
:show-files="0"
    :show-audio="0"
    :show-emojis="0"
    :show-reaction-emojis="0"
:styles="
      JSON.stringify({
        container: {
          border: `1px solid ${variable.gray2}`,
          boxShadow: 'none',
        },
        room: {
          //colorUsername: '#fff',
        },
        sidemenu: {
          background: variable.white,
          backgroundHover: '#fafbfe',
          backgroundActive: variable.elPrimary,
          colorActive: variable.white,
          borderColorSearch: '#e1e5e8',
        },
      })
    "

show-files set false can not work, but 0 is ok.
styles can not work

:show-search = "false"

show-search false or 0  can not work.

**Comment by antoine92190** [comment] 2022-09-03 21:01
I cannot reproduce any of those issues.
Could you share your repo so I can have a look?

**Comment by antoine92190** [comment] 2022-09-07 04:54
Closing this until I can reproduce

**Closed by antoine92190** 2022-09-07 04:54 UTC
Labels: bug

**Comment by 1259549061** [comment] 2022-09-09 02:22
> I cannot reproduce any of those issues. Could you share your repo so I can have a look?

![image](https://user-images.githubusercontent.com/28998743/189258617-a8f8c5c5-0e57-48f0-b2e6-fb151f516874.png)
look at this， It is easy to appear

**Comment by NINI1988** [comment] 2022-10-10 12:41
You have to remove the colons before the boolean properties.
So write:
```
show-emojis="false"
```
instead of:
```
:show-emojis="false"
```
