### ISSUE TITLE
 ERROR  Failed to compile with 1 error                                                                                                                                                            

### ISSUE THREAD

**Issue by omermaksutii** [antoine92190/vue-advanced-chat#178] opened 2021-07-05 17:53 UTC
ERROR  Failed to compile with 1 error                                                                                                                                                            
This relative module was not found:

* ./src/main.ts in multi (webpack)-dev-server/client?http://192.168.0.40:8081&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
Type checking in progress...
No type errors found

**Comment by antoine92190** [comment] 2021-07-07 07:31
Can you give more infomation?
Are you using Vue with typescript?
If yes, can you reproduce the error with a brand new blank vue typescript project?

**Comment by omermaksutii** [comment] 2021-07-08 13:38
I have not used typescript, i only cloned your project and afterwards i got the error mentioned above.

**Comment by antoine92190** [comment] 2021-07-12 06:59
I'm not sure what's the problem without more information. Can you give me access to your repo?

**Comment by 0xbul1** [comment] 2021-07-14 01:51
same error with me

maybe its same problem like #93 

if i go in `demo` folder and serve it success

just the machine has install typescript ,the error like main.ts. ignore it, haha

**Comment by antoine92190** [comment] 2021-07-15 17:15
Closing this as @0xbul1 seems to be right. You need to go in demo folder to serve the project.

**Closed by antoine92190** 2021-07-15 17:15 UTC
Labels: bug
