### ISSUE TITLE
room-id prop - is it working?

### ISSUE THREAD

**Issue by TimurZur** [antoine92190/vue-advanced-chat#361] opened 2022-09-22 13:08 UTC
I didn't quite understand from the documentation how the room-id prop should work. If I write some room-id on mounted to load messages only for this room, I get an error.

If this is not a bug, then please tell me how to use the room-id correctly to show (fetch) messages for a specific room.

For example, I want to show messages for room 13 using the link:
`mychat.com/?chatId=13`

Here's what's in the template (Removed unnecessary props just to show):
```
        <vue-advanced-chat
            :room-id="currentRoomId"
        />
```

Data (Removed unnecessary):
```
    data() {
        return {
            currentRoomId: null,
        }
    },
```

Here's what's on mounted
```
mounted() {
        this.loadingRooms = true;
        this.messagesLoaded = false;
        Nova.request().get(API_PREFIX + 'user')
            .then(data => {
             ...
            })
            .then(() => {
                const urlSearchParams = new URLSearchParams(window.location.search);
                const params = Object.fromEntries(urlSearchParams.entries());
                if (params['chatId']) {
                    this.currentRoomId = parseInt(params['chatId']);
                }
            })
    },
```

And here is the error:
![image](https://user-images.githubusercontent.com/41179341/191754751-31cf23f6-13a4-4ae0-8548-822a9694e769.png)

**Comment by antoine92190** [comment] 2022-09-22 14:21
All prop ids should be strings, have you tried to convert it as a string?
Which vue version are you using?
Which chat version are you using?

**Comment by TimurZur** [comment] 2022-09-22 14:27
> All prop ids should be strings, have you tried to convert it as a string? Which vue version are you using? Which chat version are you using?

Yes, I tried to convert it as a string, same result.

"vue-advanced-chat": "^2.0.3"
Vue: 3.2.38

**Comment by antoine92190** [comment] 2022-09-22 16:15
`room-id` is working fine on my side. Could you give me access to your repo, or reproduce a minimal example so I can reproduce?

**Comment by TimurZur** [comment] 2022-09-22 16:21
> `room-id` is working fine on my side. Could you give me access to your repo, or reproduce a minimal example so I can reproduce?

Okay, I'll put together a project and send it tomorrow (laravel + nova + vue-advanced-chat).

**Comment by antoine92190** [comment] 2022-09-22 16:24
Maybe you can work with mock data, you can use this repo as a sandbox so you don't need to setup a whole project: https://github.com/antoine92190/vue-advanced-chat-sandbox

**Comment by TimurZur** [comment] 2022-09-22 16:26
> Maybe you can work with mock data, you can use this repo as a sandbox so you don't need to setup a whole project: https://github.com/antoine92190/vue-advanced-chat-sandbox

Maybe it has something to do exactly with laravel nova. Okay, thanks, I`ll check the sandbox)

**Comment by antoine92190** [comment] 2022-09-30 13:41
@TimurZur Did you have time to create a project or find a solution?

**Comment by antoine92190** [comment] 2022-10-11 11:39
Closing this until I can reproduce the issue

**Closed by antoine92190** 2022-10-11 11:39 UTC
Labels: bug

**Comment by vesper8** [comment] 2023-10-12 15:21
I just wasted 2 hours dealing with this issue. The problem is not that room-id itself has to be a string, but rather that `roomId` inside your `rooms` needs to be a string!! Ridiculous...
