### ISSUE TITLE
Search users tag

### ISSUE THREAD

**Issue by phxtung** [antoine92190/vue-advanced-chat#258] opened 2021-12-03 07:10 UTC
Can't search when username has spaces

**Comment by antoine92190** [comment] 2021-12-04 16:48
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/c608c176f2757a71c3ab4228f7ca23370b9440e0

**Comment by antoine92190** [comment] 2021-12-06 17:10
From @phxtung
> it has a bug when the name has 4 words

**Comment by antoine92190** [comment] 2021-12-06 17:13
@phxtung From the screenshot you sent in the commit, it seems the mouse cursor is not just after the username, then the tags suggestion is not displayed. This is by design. Or is there another issue?

**Comment by phxtung** [comment] 2021-12-07 01:42
> @phxtung From the screenshot you sent in the commit, it seems the mouse cursor is not just after the username, then the tags suggestion is not displayed. This is by design. Or is there another issue?

there is another issue when the name has 4 words

**Comment by antoine92190** [comment] 2021-12-26 09:52
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/199aaa29dec768472a11c00f9bd95f7bd01f4426

**Closed** 2021-12-26 10:47 UTC
Labels: bug
