### ISSUE TITLE
(BUG) error while clicking at room with empty messages

### ISSUE THREAD

**Issue by Sfinx** [antoine92190/vue-advanced-chat#18] opened 2020-08-31 09:12 UTC
Geeting this error while clicking at room with empty messages:

...
**vue.runtime.esm.js?5593:619 [Vue warn]: Error in callback for watcher "loadingMessages": "TypeError: Cannot read property 'focus' of undefined"**

found in

---> <Room>
       <ChatContainer>
         <QPage>
           <Consult> at src/pages/Consult.vue
             <QPageContainer>
               <QLayout>
                 <MainLayout> at src/layouts/MainLayout.vue
                   <App> at src/App.vue
                     <Root>
[...]
vue.runtime.esm.js?5593:1888 TypeError: Cannot read property 'focus' of undefined
    at VueComponent.focusTextarea (vue-advanced-chat.common.js?93dc:12339)
    at VueComponent.loadingMessages (vue-advanced-chat.common.js?93dc:12174)
[...]

The code is:

```
focusTextarea: function focusTextarea(disableMobileFocus) {
      if (detectMobile() && disableMobileFocus) return;
      this.$refs['roomTextarea'].focus();
    },
```

I think it should be something like:

```
if (!this.$refs['roomTextarea'] || (detectMobile() && disableMobileFocus)) return;
this.$refs['roomTextarea'].focus();
```

**Comment by antoine92190** [comment] 2020-09-01 09:06
I cannot reproduce this error, but `roomTextarea` should be available when loading is complete.
The problem with your solution is that the textarea will not be focused when entering a room when `roomTextarea` becomes available.
Could you fork the repo and replace the method `loadingMessages` (https://github.com/antoine92190/vue-advanced-chat/blob/8603e42bc3d818e24502a4efa366b5d2d4c2eb8b/src/ChatWindow/Room.vue#L323) by the snippet below and see if it fixes the issue?

 ```
loadingMessages(val) {
    if (val) this.infiniteState = null
    else setTimeout(() => this.focusTextarea(true), 0)
},
```

**Comment by antoine92190** [comment] 2020-09-01 09:08
If it fixes the issue, feel free to open a pull request, else I will implement the change myself.

**Comment by Sfinx** [comment] 2020-09-01 14:03
To reproduce the issue just try to click at room with messages = []. The proposed repo repo is more complex than my solution so sorry I will not try it

**Comment by antoine92190** [comment] 2020-09-01 14:17
I am trying to reproduce using the demo code and passing `:messages="[]"`, but there is no error on my side.
Are you correctly assigning `:messagesLoaded="true"` when messages are loaded?

You solution may be correct, but I worry that if we add this check the textarea will not auto focus when opening a room, which is not the expected behaviour.
Maybe I'm wrong, but as I cannot reproduce I cannot check.
Is it possible for you to add this check, and see if it fixes the error, while textarea is still being auto focused?

**Comment by Sfinx** [comment] 2020-09-01 14:28
No the messagesLoaded is not just true, I've followed the demo:

```
:messagesLoaded="messagesLoaded"
...

data() {
 messagesLoaded: false
}
...
methods: {
 fetchMessages({ room, options = {} }) {
      console.log('fetchMessages: room: ', room, ', options: ', options)
      return (this.messagesLoaded = true)
 }
}
```

**Comment by antoine92190** [comment] 2020-09-01 14:33
Looks fine.
Which browser are you using? Maybe it is related.
Else can you share a minimal example that would reproduce the error?

**Comment by Sfinx** [comment] 2020-09-02 08:47
It is chrome. Will try firefox and report. So will make the minimal example (I'm using quasar)

**Comment by antoine92190** [comment] 2020-09-02 08:50
Great thanks! I'm also using Chrome, so it may be related to quasar

**Comment by Sfinx** [comment] 2020-09-03 11:29
[q.tar.gz](https://github.com/antoine92190/vue-advanced-chat/files/5168165/q.tar.gz)

Please see the minimal example:

```
yarn install
quasar dev
```

It will launch the localhost:8080 webpack server and open the browser at it

Then just click the "Some room"

**Comment by Sfinx** [comment] 2020-09-03 11:32
So tried in firefox - the same error is present

**Comment by antoine92190** [comment] 2020-09-03 13:03
Thanks, I was able to reproduce, and your solution did not have any unexpected behaviour.
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/9943ee4146a82fe8d28acb274e1f7c233a6c3bbb

**Closed by antoine92190** 2020-09-03 13:03 UTC
Labels: bug

**Comment by Sfinx** [comment] 2020-09-03 13:12
Thanks !
