### ISSUE TITLE
Question: Use existing components in custom message

### ISSUE THREAD

**Issue by NielXu** [antoine92190/vue-advanced-chat#187] opened 2021-07-25 22:36 UTC
Is it possible that we can use the existing components like emoji picker and dropdown when overriding the message slot?
```javascript
<template v-slot:message="{ message }">
  // <emoji-picker/> or something
</template>
```

**Comment by antoine92190** [comment] 2021-07-26 05:53
It's not possible at the moment.
Closing this as it's a duplicate of https://github.com/antoine92190/vue-advanced-chat/issues/166

**Closed by antoine92190** 2021-07-26 05:53 UTC
