### ISSUE TITLE
FetchMessages not being fired in singleRoom mode after opening

### ISSUE THREAD

**Issue by PhantomYdn** [antoine92190/vue-advanced-chat#155] opened 2021-03-28 18:51 UTC
## Describe the bug

If chat window configured in a single room mode without any messages in a room yet: it shows infinite loading.

Per Vue debugger panel: fetch-messages not being fired. According to source code, problem seems to be exactly in this line:
https://github.com/antoine92190/vue-advanced-chat/blob/master/src/ChatWindow/Room/Room.vue#L51

So if there is no messages: fetch-messages will not be fired to load "more" messages.

## Expected behavior

Expected that "fetch-messages" will be always fired which will allow custom code to load messages to a room.

## Screenshots

![image](https://user-images.githubusercontent.com/1199285/112763979-8ea89000-8fbb-11eb-9aa6-06d46b8501d4.png)

## Device (please complete the following information)

- OS: Win10
- Browser: Chrome 82
- Package version: 0.8.3

## Additional Context

`fetch-messages` handler defined through code: not through attribute. But it seems it should not be a problem.

**Comment by antoine92190** [comment] 2021-03-30 17:58
Thanks, will check that and fix it ASAP

**Comment by antoine92190** [comment] 2021-04-05 11:46
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/7f5006405e0bf76b56f7afd2de3d5d836f052b80

**Comment by PhantomYdn** [comment] 2021-04-06 15:58
@antoine92190 , I see that you marked the issue as fixed and it seems to be included into 0.8.4, but in 0.8.4 I see exactly the same behavior: no `fetch-messages` event. The only difference which I found: it' new "internal" event when I scroll up (so it's not even reaching upper code):

![image](https://user-images.githubusercontent.com/1199285/113741047-1ece8f80-96b6-11eb-861a-a2dad247c73e.png)

**Comment by antoine92190** [comment] 2021-04-06 16:34
`fetch-messages` event is first triggered when a room is opened.
We don't need to trigger it again using infinite loading if there is no message.
Am I missing something?

**Comment by PhantomYdn** [comment] 2021-04-06 17:33
My understanding of the documentation below. Please correct me if I got something incorrectly:

1) `fetch-messages` is an event that should be used to load messages from an external source.
2) `fetch-messages` fired when:
   a. User opens a room (if it's a single room - it also fired) or switch between rooms
   b. User scrolled up to load more messages for current room

What I want to achieve:
1) Load component as lightweight as possible: so `messages=[]`
2) Load messages only when `fetch-messages` fired

**Comment by antoine92190** [comment] 2021-04-08 07:51
Yes that's how it should work. I guess you need
> fetch-messages fired when:
a. User opens a room (if it's a single room - it also fired) or switch between rooms
Is it not working?

**Comment by PhantomYdn** [comment] 2021-04-08 14:02
> Yes that's how it should work. I guess you need
> 
> > fetch-messages fired when:
> > a. User opens a room (if it's a single room - it also fired) or switch between rooms
> 
> Is it not working?

No, unfortunately. `fetch-messages` is not fired when you just open app and first room (or single room) in the app. So you have to pre-fetch and pass it to properties.

**Comment by antoine92190** [comment] 2021-04-10 08:57
Strange, I cannot reproduce.
Could you try to reproduce with this minimal example? https://github.com/antoine92190/vue-advanced-chat-sandbox

**Comment by antoine92190** [comment] 2021-04-30 23:25
@PhantomYdn Can you reproduce with this? https://github.com/antoine92190/vue-advanced-chat-sandbox

**Comment by antoine92190** [comment] 2021-06-22 05:37
I'm closing this due to inactivity. Please reopen if you can reproduce using the repo I sent above

**Closed by antoine92190** 2021-06-22 05:37 UTC
Labels: bug

**Comment by TheMangoTrain** [comment] 2021-08-22 13:18
@PhantomYdn  Correct me if I'm wrong...

Aren't you simply talking about...

On chat component mount, automatically fetch messages for first-visible-room (whatever that is) ???

I can only presume so, based on your last reply: "No, unfortunately. fetch-messages is not fired when you just open app and first room (or single room) in the app. So you have to pre-fetch and pass it to properties."
