### ISSUE TITLE
Emoji box positioned incorrectly on some screen sizes.

### ISSUE THREAD

**Issue by StefanGhiban** [antoine92190/vue-advanced-chat#290] opened 2022-03-01 06:53 UTC
## Describe the bug

This is in regards to issue #15 . This happened to me also. The emoji box is positioned incorrectly on some screen sizes.

## Steps to reproduce

Access the chat on a 13 inch screen such as the macbook air 13.

## Expected behavior

The emoji box to open correctly as it does on larger screens.

## Screenshots

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/47953165/156119587-199e3007-46c4-462b-8e49-d9b3eff4bb0d.png">

## Device (please complete the following information)

- OS: macOs Monterrey 12.2.1
- Browser: Chrome
- Package version: 1.5.3

**Comment by antoine92190** [comment] 2022-03-06 10:18
I cannot reproduce using responsive dev tools on Google Chrome. Could you share a video so I can see the behaviour better?

**Comment by StefanGhiban** [comment] 2022-03-06 13:11
https://user-images.githubusercontent.com/47953165/156924684-6644e032-71ad-4606-8e3c-3fc7ef5b98a9.mov

@antoine92190

**Comment by antoine92190** [comment] 2022-03-22 06:53
I couldn’t reproduce yet on my side, not sure why. You can reproduce on the public demo website right?

**Comment by StefanGhiban** [comment] 2022-03-22 11:07
@antoine92190 yes, to an extent. It is not as bad, but it still happens on some resolutions.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/47953165/159468357-ed7d7eb5-8702-40ad-b0ca-626ce821a556.png">

**Comment by antoine92190** [comment] 2022-04-12 05:09
Have you refreshed the page every time you resized the window? This might solve the issue?

**Comment by antoine92190** [comment] 2022-05-07 07:42
Closing this until I get an answer to my previous message.

**Closed by antoine92190** 2022-05-07 07:42 UTC
Labels: bug
