### ISSUE TITLE
Errors when sending files and copy pasting text

### ISSUE THREAD

**Issue by Alisonispig** [antoine92190/vue-advanced-chat#236] opened 2021-11-07 11:50 UTC
send file is this

![image](https://user-images.githubusercontent.com/29892659/140643629-a689e39e-17c9-455c-a8bb-fd575c2010ae.png)

ctrl v text 

![image](https://user-images.githubusercontent.com/29892659/140643648-fe1c3a9f-f6ec-4497-8111-2703c52cd3ec.png)

I didn't find this error when I entered the text

**Comment by Alisonispig** [comment] 2021-11-07 13:39
I tried to downgrade to 1.2.2 and didn't find this problem

**Comment by antoine92190** [comment] 2021-11-07 15:35
I cannot reproduce.
Which browser are you using? Is your project built with vue or another framework?
Could you share your repo so I can try to reproduce and fix the issue?

**Comment by Alisonispig** [comment] 2021-11-08 02:08
Of course, I use vue, which is my dependency
![image](https://user-images.githubusercontent.com/29892659/140673066-58545627-8005-4994-b446-650c10fdcd8d.png)

I use the edge browser ,the version is  95.0.1020.40

This is my calling code, 
`      <chat-window
          :height="pageHeight"
          :styles="styles"
          :current-user-id="currentUserId"
          :show-add-room="false"
          :room-id="roomId"
          :rooms="loadedRooms"
          :loading-rooms="loadingRooms"
          :messages="messages"
          :messagesLoaded="messageLoaded"
          :rooms-loaded="roomsLoaded"
          :text-messages="textMessages"
          :message-actions="messageActions"
          @send-message="sendMessage"
          @add-room="addRoom"
          @fetch-messages="fetchMessage"
          @send-message-reaction="sendMessageReaction"
      >`

`    const sendMessage = async ({content, roomId, files, replyMessage}) => {
      let reply;
      if (replyMessage) {
        reply = {
          content: replyMessage.content,
          senderId: replyMessage.senderId,
        }
      }
      const message = {
        senderId: currentUserId.value,
        content,
        roomId,
        replyMessage: reply,
        files: []
      }

      // 如果存在文件, 则把文件加入到上传列表,等待上传完毕后发送
      if (files) {
        waitSendMessage.value.push(message)
        await addFiles(files, roomId, (file, isOver) => {
          sendFileMessage({
            name: file.name + '.' + file.extension,
            size: file.size,
            type: file.type,
            url: file.url,
          }, roomId, isOver)
        })
      } else {
        sendChatMessage(message)
      }
      upRoom(roomId)
    }`

If you need more information, I can still provide

**Comment by antoine92190** [comment] 2021-11-08 08:31
Can you make sure you have Vue `2.6.14` installed? This library is not compatible with vue version below

**Comment by Alisonispig** [comment] 2021-11-08 08:34
你的意思是我升级到2.6.14?

**Comment by antoine92190** [comment] 2021-11-08 08:35
Please write in english

**Comment by Alisonispig** [comment] 2021-11-08 08:37
Sorry, my English is not good and I need translation software. Do you mean I upgraded to 2.6.14?...

**Comment by antoine92190** [comment] 2021-11-08 08:38
In your dependencies I see `vue: ^2.6.11`, you need to have `vue: ^2.6.14`

**Comment by Alisonispig** [comment] 2021-11-08 08:39
OK, let me trying it

**Comment by Alisonispig** [comment] 2021-11-08 08:47
Unfortunately, it still doesn't work. It's the same as the above error

![image](https://user-images.githubusercontent.com/29892659/140711258-3c5310fe-7f14-4101-b9d3-732a94ed44dc.png)

**Comment by Alisonispig** [comment] 2021-11-08 08:56
That's how it works
![image](https://user-images.githubusercontent.com/29892659/140712262-9e67eda6-c423-4d3a-bbe4-889a15de66e7.png)
![image](https://user-images.githubusercontent.com/29892659/140712376-1b243509-2d3c-45bb-bb22-4119e936e8c4.png)
I think the problem may be the update from 1.2.2 to 1.3.0. Can you try to recall whether the new technology is used? Or changed something

**Comment by antoine92190** [comment] 2021-11-08 09:00
I will check later, but can you share your full repo with me so I can reproduce on my side? Or create a minimal example that I can run locally to reproduce?

**Comment by Alisonispig** [comment] 2021-11-08 09:03
There are too many related things in the project. It's troublesome for you to run. I'll try to do a simple project. Wait for me

**Comment by Alisonispig** [comment] 2021-11-08 10:31
I wrote a simple demo

https://1drv.ms/u/s!Au3ilgxdlAZikyd0TJJjrH25w6ot?e=yU9Amz

It may be related to my use of @ Vue / composition API,   But mistakes did occur

**Comment by Garay01** [comment] 2021-11-08 20:40
Hi I had the same problem, thanks for your reply I could solve with your answer.

**Comment by antoine92190** [comment] 2021-11-08 21:36
@Alisonispig Thanks, I can reproduce with your demo. Will fix it ASAP

**Comment by antoine92190** [comment] 2021-11-08 22:10
Should be fixed in https://github.com/antoine92190/vue-advanced-chat/commit/0b7de96de8e9d9273b3c975acb39ffe04371133f

**Comment by antoine92190** [comment] 2021-11-08 22:19
@Alisonispig Please check version `1.3.1` and let me know if the issue is fixed

**Comment by Alisonispig** [comment] 2021-11-09 03:32
is can use

**Closed** 2021-11-09 07:48 UTC
Labels: bug
