### ISSUE TITLE
Incorrect scroll behaviour

### ISSUE THREAD

**Issue by martynishin** [antoine92190/vue-advanced-chat#143] opened 2021-03-04 16:59 UTC
## Describe the bug

With the same code for fetch messages on the first page load, if the last message belongs to the current user, then scroll works correctly. If the last message belongs to another user, then scroll works incorrectly. See screenshots below.

## Steps to reproduce

1. Load a lot of messages.
2. The last message shoul belongs to another user.
3. Textarea does not scroll to the bottom.

## Expected behavior

Textarea should scroll to the bottom, as for the case, when the last message belongs to the current user.

## Screenshots

<img width="1059" alt="Снимок экрана 2021-03-03 в 14 01 49" src="https://user-images.githubusercontent.com/20871977/109803342-9af23500-7c29-11eb-81e6-abb024bc7662.png">
<img width="1059" alt="Снимок экрана 2021-03-03 в 14 02 14" src="https://user-images.githubusercontent.com/20871977/109803345-9c236200-7c29-11eb-8b86-bd3ea752f111.png">

## Device (please complete the following information)

MacBook Pro 15"

**Comment by martynishin** [comment] 2021-03-05 12:49
The same scroll issue when the current user loads a page and does nothing. Opponent sends a message. Current user receives this message.

<img width="1062" alt="Снимок экрана 2021-03-05 в 14 45 36" src="https://user-images.githubusercontent.com/20871977/110117392-74ff9880-7dc1-11eb-9965-d634d6853ecc.png">

**Comment by antoine92190** [comment] 2021-03-05 17:43
Thanks, will fix this ASAP

**Comment by antoine92190** [comment] 2021-03-06 00:00
I cannot reproduce. Are you testing with latest version `0.8.0`?
If yes, can you reproduce the issue using this repo: https://github.com/antoine92190/vue-advanced-chat-sandbox

Or maybe it's related to the textarea heigh which is too big on your side. Is the size of the textarea smaller when running the repo I sent above? This is what I have on my side:
<img width="1792" alt="Screen Shot 2021-03-06 at 00 59 27" src="https://user-images.githubusercontent.com/16256207/110187018-3dbbd680-7e17-11eb-8d34-3c9bd01b45e0.png">

**Comment by martynishin** [comment] 2021-03-06 07:57
Yes, I've tested on 0.8.0 version.
Moreover, the same behaviour with your repo: https://github.com/antoine92190/vue-advanced-chat-sandbox

<img width="1431" alt="Снимок экрана 2021-03-06 в 09 55 56" src="https://user-images.githubusercontent.com/20871977/110199667-2b1abf00-7e62-11eb-90f3-7af3e8238752.png">

**Comment by antoine92190** [comment] 2021-03-06 08:18
Ok so this happens on your side without any action/click from you right? And if you scroll down you see the "NEW" message right?

**Comment by antoine92190** [comment] 2021-03-06 08:29
Oh sorry, the repo I sent you is use vue-advanced-chat 0.7.8
I updated the version, could you retest after running `npm install` and confirm the issue is still there?

**Comment by martynishin** [comment] 2021-03-06 08:37
The same with 0.8.0
Just refresh the page and have this screenshot. No actions/clicks. Scroll down and see the "NEW".

**Comment by antoine92190** [comment] 2021-03-06 08:43
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/5f635ed2aa5fc2765398019d23cf14b46c395ae6
Could you install the last GitHub version of the chat by running `npm i https://github.com/antoine92190/vue-advanced-chat/tarball/master` and let me know if it works?

**Comment by martynishin** [comment] 2021-03-06 09:05
It works correctly with this version: https://github.com/antoine92190/vue-advanced-chat/tarball/master

**Comment by martynishin** [comment] 2021-03-06 09:09
But if the browser console is closed. If it opened and located at the bottom, it works like before.

<img width="1440" alt="Снимок экрана 2021-03-06 в 11 09 40" src="https://user-images.githubusercontent.com/20871977/110201581-74700c00-7e6c-11eb-8d84-70148ae59499.png">

**Comment by martynishin** [comment] 2021-03-06 09:33
And if not set `this.messagesLoaded = true` that means you have pagination and can load more messages, scroll works incorrectly too.

**Comment by martynishin** [comment] 2021-03-06 10:14
I can fix that by adding this crutch, but I guess would be better move something like this under the hood.
P.S. with the same crutch I can fix scroll after receiving message from another user.

<img width="859" alt="Снимок экрана 2021-03-06 в 12 09 04" src="https://user-images.githubusercontent.com/20871977/110203192-56f37000-7e75-11eb-9b42-c07d5aca5648.png">

**Comment by antoine92190** [comment] 2021-03-06 10:17
> P.S. with the same crutch I can fix scroll after receiving message from another user.

You mean the scroll issue when the console is opened at the bottom?

**Comment by martynishin** [comment] 2021-03-06 10:20
> > P.S. with the same crutch I can fix scroll after receiving message from another user.
> 
> You mean the scroll issue when the console is opened at the bottom?

Yes. Moreover, it works with old version, e.g. 0.7.8

**Comment by antoine92190** [comment] 2021-03-07 09:52
I cannot reproduce.
I updated https://github.com/antoine92190/vue-advanced-chat-sandbox, could you check if you can reproduce there?
Otherwise can you tell me how to reproduce using the repo above?

**Comment by antoine92190** [comment] 2021-03-07 09:56
I still think the issue may be because of your textarea height, and it's probably coming from your own project as your screenshot using my repo has the correct textarea height: https://github.com/antoine92190/vue-advanced-chat/issues/143#issuecomment-791891925

**Comment by martynishin** [comment] 2021-03-08 17:01
1. Use this repo: https://github.com/antoine92190/vue-advanced-chat-sandbox

2. Move rooms array from mounted() to data()

```
data() {
        return {
            currentUserId: 1234,
            rooms: [
                {
                    roomId: 1,
                    roomName: 'Room 1',
                    avatar: 'https://66.media.tumblr.com/avatar_c6a8eae4303e_512.pnj',
                    users: [
                        { _id: 1234, username: 'John Doe' },
                        { _id: 4321, username: 'John Snow' }
                    ]
                }
            ],
            messages: [],
            messagesLoaded: false
        }
    },
```

3. Change senderId in addMessages to another. Example:
```
addMessages(reset) {
            const messages = []
            for (let i = 0; i < 30; i++) {
                messages.push({
                    _id: reset ? i : this.messages.length + i,
                    content: `${reset ? '' : 'paginated'} message ${i + 1}`,
                    senderId: 12345,
                    username: 'John Doe',
                    date: '13 November',
                    timestamp: '10:20'
                })
            }
            return messages
        },
```

4. Refresh the chat page in your browser.

**Comment by antoine92190** [comment] 2021-03-08 18:23
Could you check if latest version `npm i https://github.com/antoine92190/vue-advanced-chat/tarball/master` works?

**Comment by martynishin** [comment] 2021-03-09 08:46
No, it doesn't work. Steps to reproduce above.

<img width="1440" alt="Снимок экрана 2021-03-09 в 10 45 27" src="https://user-images.githubusercontent.com/20871977/110443422-9237ae00-80c4-11eb-9fcd-43710af70719.png">

**Comment by martynishin** [comment] 2021-03-09 13:14
I've found one more similar issue. If you use return statement in fetchMoreRooms(), then spinner doesn't disappear.

```
fetchMoreRooms() {
            if (this.a > 3) this.roomsLoaded = true

            let rooms = []
            setTimeout(() => {
                if (this.a > 3) return (this.roomsLoaded = true)

                this.a++
                for (let i = 0; i < 10; i++) {
                    rooms.push({
                        roomId: Math.random(),
                        roomName: 'Room 1',
                        avatar: 'https://66.media.tumblr.com/avatar_c6a8eae4303e_512.pnj',
                        users: [
                            { _id: 1234, username: 'John Doe' },
                            { _id: 4321, username: 'John Snow' }
                        ]
                    })
                }

                this.rooms = [...this.rooms, ...rooms]
            }, 1000)
        }
```

<img width="324" alt="Снимок экрана 2021-03-09 в 15 13 57" src="https://user-images.githubusercontent.com/20871977/110475888-13ee0280-80ea-11eb-8cdd-0b924b356632.png">

**Comment by antoine92190** [comment] 2021-03-12 08:52
> No, it doesn't work. Steps to reproduce above.
> 
> <img alt="Снимок экрана 2021-03-09 в 10 45 27" width="1440" src="https://user-images.githubusercontent.com/20871977/110443422-9237ae00-80c4-11eb-9fcd-43710af70719.png">

It's working on my side. I updated https://github.com/antoine92190/vue-advanced-chat-sandbox with your reproducible steps, let me know if you have the issue there. Don't forget to run `npm install` to make sure you are using the latest version.

**Comment by antoine92190** [comment] 2021-03-12 09:14
> fetchMoreRooms() {
>             let rooms = []
>             setTimeout(() => {
>                 if (this.a > 3) return (this.roomsLoaded = true)
> 
>                 this.a++
>                 for (let i = 0; i < 10; i++) {
>                     rooms.push({
>                         roomId: Math.random(),
>                         roomName: 'Room 1',
>                         avatar: 'https://66.media.tumblr.com/avatar_c6a8eae4303e_512.pnj',
>                         users: [
>                             { _id: 1234, username: 'John Doe' },
>                             { _id: 4321, username: 'John Snow' }
>                         ]
>                     })
>                 }
> 
>                 this.rooms = [...this.rooms, ...rooms]
>             }, 1000)
>         }

Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/30e5b5b8386b2390359850aed6adf33d21e32fcf
You can test with latest version `npm i https://github.com/antoine92190/vue-advanced-chat/tarball/master`

**Closed** 2021-03-12 17:20 UTC
Labels: bug, priority
